<button class='novoprojeto btn_back' onclick='voltar()'>Voltar</button>
<?php
    $this->form->setAction($this->url());
    $pais = $this->pais;
    echo $this->form;
//coment2

?>
<script type="text/javascript">
    $(document).ready(function() {
        $('.fancybox').fancybox();
    });

    $("#instituicao-botaoPesquisa").click(function() {
        $('<a class="fancybox fancybox.iframe" href="instituicoes/treeview">pesquisar</a>').fancybox({
            overlayShow: true
        }).click();
    });
</script>

<script type="text/javascript">
    carregaEstados(<?php echo $pais; ?>);

    function carregaEstados(valor){
        if (valor == 76)
        {
            $('#instituicao-estados_id-label').css('display','block');
            $('#instituicao-estados_id-element').css('display','block');
            $('#instituicao-cidade_id-label').css('display','block');
            $('#instituicao-cidade_id-element').css('display','block');
            $('#instituicao-cidade_text-label').css('display','none');
            $('#instituicao-cidade_text-element').css('display','none');
            $('#instituicao-cidade_text').attr('disabled' , 'disabled');
            $.ajax({
                url: '/instituicoes/selectestados/id/'+valor,
                dataType:'html',
                type:'GET',
                success: function(data){
                    $('select#instituicao-estados_id').html(data);
                }
            })
            carregaCidades('0');
        }
        else
        {
            $('#instituicao-cidade_text').removeAttr('disabled');
            carregaCidades(99999);
        };
    }

    function carregaCidades(valor){
        if (valor !== 99999)
        {
            $.ajax({
                url: '/instituicoes/selectcidades/id/'+valor,
                dataType:'html',
                type:'GET',
                success: function(data){
                    $('select#instituicao-cidade_id').html(data);
                }
            })
        }
        else
        {
            $('#instituicao-estados_id-label').css('display','none');
            $('#instituicao-estados_id-element').css('display','none');
            $('#instituicao-cidade_id-label').css('display','none');
            $('#instituicao-cidade_id-element').css('display','none');
            $('#instituicao-cidade_text-label').css('display','block');
            $('#instituicao-cidade_text-element').css('display','block');
        }
        ;
    }
    function voltar()
    {
        top.location.href = '/../instituicoes/';

    }
</script>

<style>
    .novoprojeto {
        float:right;
    }
</style>
