<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir a instituicao?");
        if (answer) {
            top.location.href = '/../instituicoes/excluir/instituicao_id/'+id;
        }
        else {
            alert("A instituicao não foi excluído!");
        }
    }
</script>
<script>
    function editar(id)
    {
        top.location.href = '/../instituicoes/adicionar/instituicao_id/'+id;

    }
</script>

<?php
$id = $this->id;

echo "<button class=\"right btn_delete\" onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button class=\"right btn_edit\" onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>