<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<style>
    table * *{
        text-align: center;
    }
</style>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Nome da Instituição</th>
        <th>Projetos Ativos</th>
        <th>Projetos Arquivados</th>
        <th>Tipo Instituição</th>
        <th>Responsável</th>
    </tr>
    </thead>
    <tbody>

    <?php

    foreach($this->instituicao as $row)
    {
        //$row = $row->toArray();
        echo "<tr id='".$row['instituicao_id']."'>";
        echo "<td><a href='/instituicoes/detalhes/instituicao_id/{$row['instituicao_id']}'>" .$row['nome']. "</a></td>";
        echo "<td>" .$row['ativo']. "</td>";
        echo "<td>" .$row['arquivado']. "</td>";
        echo "<td>" .$row['tipo']. "</td>";
        echo "<td>" .$row['responsavel']. "</td>";
    }

    echo "</tr>";
    echo "</tbody></table>";
?>