<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            //"bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>

<table id='table_id' border='1'>
    <thead>
    <tr>
        <th>Nome</th>
        <th>siglas</th>
        <th>cnpj</th>
        <th>responsavel</th>
        <th>telefone</th>
        <th>e-mail</th>
        <th>telefone 2</th>
        <th>fax</th>
        <th>endereço</th>
        <th>complemento</th>
        <th>País</th>
        <th>Estado</th>
        <th>Cidade</th>
        <th>CEP</th>
        <th>website</th>
        <th>Tipo</th>
        <th>descriçao</th>
        <th>Pai Id</th>
        <th>Denominacao</th>
    </tr>
    </thead>
    <tbody>

    <?php

    foreach($this->instituicao as $row)
    {
        //$row = $row->toArray();
        echo "<tr id='".$row['instituicao_id']."'>";
        echo "<td>" .$row['nome']. "</td>";
        echo "<td>" .$row['siglas']. "</td>";
        echo "<td>" .$row['cnpj']. "</td>";
        echo "<td>" .$row['responsavel']. "</td>";
        echo "<td>" .$row['telefone']. "</td>";
        echo "<td>" .$row['e_mail']. "</td>";
        echo "<td>" .$row['telefone2']. "</td>";
        echo "<td>" .$row['fax']. "</td>";
        echo "<td>" .$row['endereco']. "</td>";
        echo "<td>" .$row['complemento']. "</td>";
        echo "<td>" .$row['pais_nome']. "</td>";
        echo "<td>" .$row['uf']. "</td>";
        echo "<td>" .$row['cidade_nome']. "</td>";
        echo "<td>" .$row['cep']. "</td>";
        echo "<td>" .$row['website']. "</td>";
        echo "<td>" .$row['tipo']. "</td>";
        echo "<td>" .$row['descricao']. "</td>";
        echo "<td>" .$row['pai_id']. "</td>";
        echo "<td>" .$row['denominacao_nome']. "</td>";
    }

    echo "</tr>";
    echo "</tbody></table>";
?>