<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<script>
    $(document).ready(function() {

        $('#table_id_usuario').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });

        $('#table_id_contato').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });
    });

</script>
<style>
    table * *{
        text-align: center;
    }
    .novousuario {
        float:right;
    }
    #tabs{
        width: 50%;
    }
    ul.treeview{
        width: 40%;
        position: absolute;
        top:0;
        right: 0;
    }
    .dataTables_wrapper .ui-toolbar{
        width: 97%;
    }
</style>

<script type="text/javascript">
    $(document).ready(function() {
        $('.fancybox').fancybox();
    });

    function retornaId(nome,id)
    {
        parent.$('#instituicao-ac').val(nome);
        parent.$('#instituicao-instituicao_id').val(id);
        parent.$.fancybox.close();
    }
</script>

<div id="tabs">
    <div id="tabs-1">
        <table id='table_id_usuario'>
            <thead>
            <tr>
                <th>Nome Instituição</th>
            </tr>
            </thead>
            <tbody>

            <?php

            foreach($this->tree as $row) // "$this->usuarios" nome da variável definida no controller
            {

                echo "<tr id='".$row['instituicao_id']."'>";
                echo "<td><a href='/instituicoes/treeview/instituicao_id/{$row['instituicao_id']}'>" .$row['nome']. "</a></td>";
                echo "</tr>";
            }
            ?>
            </tbody>
        </table>
    </div>
</div>