<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<script>
    $(document).ready(function() {

        $('#table_id_usuario').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });

        $('#table_id_contato').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });
    });

</script>
<script>
    function adicionar()
    {
        top.location.href = '/../usuarios/adicionar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novousuario {
        float:right;
    }
</style>

<div class="botoes_superiores">
    <button class='novousuario btn_add' onclick='adicionar()'>Novo Usuario</button>
</div>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Usuario</a></li>
        <li><a href="#tabs-2">Contato</a></li>
    </ul>
    <div id="tabs-1">
        <table id='table_id_usuario'>
            <thead>
            <tr>
                <th>Usuário</th>
                <th>Nome Usuário</th>
                <th>Instituição</th>
            </tr>
            </thead>
            <tbody>

            <?php

            foreach($this->usuario as $row) // "$this->usuarios" nome da variável definida no controller
            {

                echo "<tr id='".$row['usuario_id']."'>";
                echo "<td>" .$row['u.sobrenome']. "</td>";
                echo "<td><a href='/usuarios/detalhes/usuario_id/{$row['usuario_id']}'>" .$row['u.nome']. "</a></td>";
                echo "<td>" .$row['i.nome']. "</td>";
                echo "</tr>";
            }
            ?>
            </tbody>
        </table>
    </div>
    <div id="tabs-2">
        <table id='table_id_contato'>
            <thead>
            <tr>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Instituição</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($this->usuariocontatos as $row) // "$this->usuarios" nome da variável definida no controller
            {
                echo "<tr id='".$row['usuario_id']."'>";
                echo "<td><a href='/usuarios/detalhescontatos/usuario_id/{$row['usuario_id']}'>" .$row['u.nome']. "</a></td>";
                echo "<td>" .$row['u.sobrenome']. "</td>";
                echo "<td>" .$row['i.nome']. "</td>";
                echo "</tr>";
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
