<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir a pasta?");
        if (answer) {
            top.location.href = '/../pastaarquivos/excluir/pasta_arquivo_id/'+id;
        }
        else {
            alert("A pasta não foi excluída!");
        }
    }
</script>
<script>
    function editar(id)
    {
        top.location.href = '/../pastaarquivos/adicionar/pasta_arquivo_id/'+id;

    }
</script>

<?php
$id = $this->id;
// comentario
echo "<button onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>