<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar()
    {
        top.location.href = '/../pastaarquivos/adicionar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novoprojeto {
        float:right;
    }
</style>
<button class='novoprojeto' onclick='adicionar()'>Novo Pasta</button>

<table id='table_id' border='1'>
    <thead>
    <tr>

        <th>Pasta</th>
        <th>Projeto</th>
        <th>Tarefa</th>

    </tr>
    </thead>
    <tbody>

    <?php

    foreach($this->pastaarquivo as $row)
    {
        echo "<tr id='".$row['pa.pasta_arquivo_id']."'>";
        echo "<td><a href='/pastaarquivos/detalhes/pasta_arquivo_id/{$row['pa.pasta_arquivo_id']}'>" . $row['pa.nome_pasta'] . "</a></td>";
        echo "<td>" .   $row['p.nome'] . "</td>";
        echo "<td >" .  $row['t.nome'] . "</td>";

        echo "</tr>";
    }
    echo "</tbody></table>";
?>
