<?php
$this->form->setAction($this->url());
echo $this->form;
?>

<script type="text/javascript" src="js/jquery.ui.combogrid-1.6.2.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $( "#orcamento-rubrica").combogrid({
            debug:true,
            colModel: [{'columnName':'codigo_rubrica','width':'45','label':'Código Rúbrica'},{'columnName':'descricao','width':'45','label':'Descrição'}],
            url: 'orcamentos/combogridrubrica/',
            select: function( event, ui ) {
                $("#orcamento-rubrica").val( ui.item.codigo_rubrica + ' - ' +  ui.item.descricao );
                $("#orcamento-rubrica_id").val( ui.item.rubrica_id );
                return false;
            }
       });
        $saldo =  $('#orcamento-saldo');
        $saldo.val(mask($saldo.val(), '###.###.###,##'));
    });


    function maskPre(val, msk, pre) {

        val = val.replace(RegExp('[' + msk.replace(/#/g, '') + ']', 'g'), '')

        if (val.length > 0) {
            val = pre + val
        }

        mskVal = ''
        v = val.length - 1
        for (m = msk.length - 1; m >= 0 && v >= -msk.indexOf('#'); --m) {
            if ('#' != msk.charAt(m)) {
                mskVal = msk.charAt(m) + mskVal
                if ('#' != msk.charAt(m - 1))
                    continue
                --m
            }
            mskVal = val.charAt(v) + mskVal
            v--

        }

        if (pre.length > 0) {
            mskVal = mskVal.replace(RegExp('^' + pre.charAt(0) + '+', 'g'), '')
        }

        return mskVal

    }
    function mask(val, msk) {

        return maskPre(val, msk, '')
    }
</script>
