<?php
$projeto_id = $this->pid;
?>


<script>
    $(document).ready(function() {
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/<?php echo $projeto_id; ?>">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
        var projeto_id = <?php echo $projeto_id; ?>;
    });

</script>

<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id, projeto_id)
    {
        var answer = confirm("Deseja realmente excluir o orçamento?");
        if (answer) {
            top.location.href = '/../orcamentos/excluir/orcamento_id/'+ id + '/projeto_id/' + projeto_id ;
        }
        else {
            alert("O orçamento não foi excluído!");
        }
    }
</script>
<script>
    function editar(id, pid)
    {
        top.location.href = '/../orcamentos/adicionar/orcamento_id/'+id+ '/projeto_id/' + pid ;

    }
</script>

<?php
 $id = $this->id;

echo "<button onclick='confirmarExclusao($id, $projeto_id)'>Excluir</button>";
echo "<button onclick='editar($id, $projeto_id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>
