<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir o orçamento?");
        if (answer) {
            top.location.href = '/../orcamento/excluir/orcamento_id/'+id;
        }
        else {
            alert("O orçamento não foi excluído!");
        }
    }
</script>
<script>
    function editar(id)
    {
        top.location.href = '/../orcamento/adicionar/orcamento_id/'+id;

    }
</script>

<?php
 $id = $this->id;

echo "<button onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>