<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../orcamentos/adicionar/projeto_id/'+projeto_id;

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novoorcamento {
        float:right;
    }
</style>

<?php
$projeto_id = $this->pid;
echo "<button class='novoorcamento btn_add' onclick='adicionar($projeto_id)'>Novo Orçamento</button>";
?>

<table id='table_id'>
    <thead>
    <tr>
        <!-- Código; Rubrica; Natureza da despesa; Destinação; Valor da Rubrica; Valor empenhado; Saldo orçamentário Valor desembolsado; Valor total;
        Valor estimado, Total empenhado, Saldo orçamentário, saldo financeiro -->
        <th> </th>
        <th>Código</th>
        <th>Natureza da Despesa</th>
        <th>Destinatário</th>
        <th>Valor da Rubrica</th>
<!--        <th>Orçamento Disponibilizado</th>-->
        <th>Empenhado</th>
        <th>Saldo Orcam.</th>
        <th>Desembolsado</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $i = 1;
    foreach($this->orcamentos as $row)
    {
    $valor_empenho = number_format(0 + ($row['valor_empenho'] - $row['valor_pre_empenho']), 2, '.', '');
    $saldo_orcamentario =  number_format(0 + ($row['SUM( o.valor_orcamento )'] - $valor_empenho), 2, '.', '');
    $valor_desembolso = number_format(0 + $row['valor_desembolso'], 2, '.', '');

        //$row = $row->toArray();
    echo "<tr id='".$row['orcamento_id']."'>";
    echo "<td>" .   $i . "</td>";
    echo "<td>" .   $row['codigo_rubrica'] . "</td>";
    echo "<td>" . $row['descricao'] . "</a></td>";
    echo "<td>" .   $row['nome_destinatario'] . "</td>";
    echo "<td >" .  $row['SUM( o.valor_orcamento )'] . "</td>";
  //  echo "<td >" .  $row[''] . "</td>";
    echo "<td >" .  $valor_empenho . "</td>";
    echo "<td >" .  $saldo_orcamentario . "</td>";
    echo "<td >" .  $valor_desembolso . "</td>";
    echo "</tr>";
    $i++;
    }
    echo "</tbody></table>";
?>