<?php
$projeto_id = $this->pid;
?>

<script xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/'+<?php echo $projeto_id; ?>+'">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../orcamentos/adicionar/projeto_id/'+projeto_id;

    }

</script>
<style>
    table * *{
        text-align: center;
    }
    .novoorcamento {
        float:right;
    }
</style>

<?php

echo "<button class='menu_financeiro'>Menu Financeiro</button>";
echo "<button class='novoorcamento btn_add' onclick='adicionar($projeto_id)'>Novo Orçamento</button>";
?>

<table id='table_id'>
    <thead>
    <tr>
        <!-- Código; Rubrica; Natureza da despesa; Destinação; Valor da Rubrica; Valor empenhado; Saldo orçamentário Valor desembolsado; Valor total;
        Valor estimado, Total empenhado, Saldo orçamentário, saldo financeiro -->
        <th> </th>
        <th>Código</th>
        <th>Natureza da Despesa</th>
        <th>Destinatário</th>
        <th>Valor da Rubrica</th>
<!--        <th>Orçamento Disponibilizado</th>-->
        <th>Empenhado</th>
        <th>Saldo Orcam.</th>
        <th>Desembolsado</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $i = 1;
    $somaRubrica = 0;
    $somaEmpenho = 0;
    $somaSaldoOrc = 0;
    $somaDesembolso = 0;
    $decimalfilter = new Zend_Filter_DecimalFilter();
    $orcamentoProjeto = $decimalfilter->filter($this->orcamentoProjeto[0]['p.orcamento']);
    $valor_cronograma_financeiro = number_format(0 + $this->orcamentos[0]['valor_recebido'], 2, '.', '');

    foreach($this->orcamentos as $row)
    {
    $valor_empenho = number_format(0 + ($row['valor_empenho'] + $row['valor_pre_empenho']), 2, '.', '');
    $saldo_orcamentario =  number_format(0 + ($row['SUM( o.valor_orcamento )'] - $valor_empenho), 2, '.', '');
    $valor_desembolso = number_format(0 + $row['valor_desembolso'], 2, '.', '');
    $somaRubrica = $somaRubrica + $row['SUM( o.valor_orcamento )'];
    $somaEmpenho = $somaEmpenho + $valor_empenho;
    $somaSaldoOrc = $somaSaldoOrc + $saldo_orcamentario;
    $somaDesembolso = $somaDesembolso + $valor_desembolso;


        //$row = $row->toArray();
    echo "<tr id='".$row['orcamento_id']."'>";
    echo "<td>" .   $i . "</td>";
    echo "<td><a href='/orcamentos/detalhes/orcamento_id/" .  $row['orcamento_id'] . "'>" .  $row['codigo_rubrica'] . "</a></td>";
    echo "<td>" . $row['descricao'] . "</a></td>";
    echo "<td>" .   $row['nome_destinatario'] . "</td>";
    echo "<td >" .  $decimalfilter->filter($row['SUM( o.valor_orcamento )']) . "</td>";
  //  echo "<td >" .  $row[''] . "</td>";
    echo "<td >" .  $decimalfilter->filter($valor_empenho) . "</td>";
    echo "<td >" .  $decimalfilter->filter($saldo_orcamentario) . "</td>";
    echo "<td >" .  $decimalfilter->filter($valor_desembolso) . "</td>";
    echo "</tr>";
    $i++;


    }
    echo "</tbody></table>";

    echo "</br>";
    echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
    echo "<thead style='background-color: #E2E4FF;'>";
    echo "<tr>";
    echo "<th> Orçamento Previsto</th>";
    echo "<th> Total Rubrica</th>";
    echo "<th> Orçamento Disponibilizado</th>";
    echo "<th> Total Empenhado</th>";
    echo "<th> Saldo Orçamentário</th>";
    echo "<th> Total Desembolsado</th>";
    echo "<th> Saldo Financeiro</th>";
    echo "</tr>";
    echo "</thead>";

    echo "<tbody style='color:green;'>";
    echo "<tr>";
    echo "<td>" . $orcamentoProjeto . "</td>";
    echo "<td>" . $decimalfilter->filter($somaRubrica) . "</td>";
    echo "<td> TODO </td>";
    echo "<td>" . $decimalfilter->filter($somaEmpenho) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaSaldoOrc) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaDesembolso) . "</td>";
    echo "<td>" . $decimalfilter->filter($valor_cronograma_financeiro - $valor_desembolso) . "</td>";

    echo "</tr>";
    echo "</tbody>";
    echo "</table>";
    echo "</br></br></br>";

?>
