<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir o usuario?");
        if (answer) {
            top.location.href = '/../usuarios/excluir/usuario_id/'+id;
        }
        else {
            alert("O usuário não foi excluído!");
        }
    }

    function editar(id)
    {
        top.location.href = '/../usuarios/adicionar/usuario_id/'+id;

    }
</script>

<?php
$id = $this->id;

echo "<button class=\"right btn_delete\" onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button class=\"right btn_edit\" onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>