<script type="text/javascript">
    $(function() {
        $( "#tabs" ).tabs();
    });

    $(document).ready(function() {

        $('#table_id_usuario').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });

        $('#table_id_contato').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });
    });

    function retornarProjetos()
    {

        linhas_checadas = $('input:checked').parent('td').parent('tr');

        $.each(linhas_checadas, function(index,value){
           var id = $(value).children('td:eq(0)').children('input').val();
           var nome =  $(value).children('td:eq(1)').html();
           parent.agregar(id,nome);
        });
        parent.$.fancybox.close();
    }
</script>

<style>
    table * *{
        text-align: center;
    }
    .novousuario {
        float:right;
    }
    #tabs{
        width: 50%;
    }
    ul.treeview{
        width: 40%;
        position: absolute;
        top:0;
        right: 0;
    }
    .dataTables_wrapper .ui-toolbar{
        width: 97%;
    }
</style>

<div id="tabs">
    <div id="tabs-1">
        <table id='table_id_usuario'>
            <thead>
            <tr>
                <th></th>
                <th>Nome Projeto</th>
            </tr>
            </thead>
            <tbody>

            <?php

            foreach($this->fancy as $row) // "$this->usuarios" nome da variável definida no controller
            {
                echo "<tr id='".$row['projeto_id']."'>";
                echo "<td><input type='checkbox' name='projetosselecionados[]' value='".$row['projeto_id']."'></td>";
                echo "<td>" .$row['nome']. "</td>";
                echo "</tr>";
            }

            ?>
            </tbody>
        </table>

    </div>
</div>
<button onclick="retornarProjetos()">Enviar</button>