   <?php    $result=$this->permissoes;
            $nomeprojetos=$this->nomeprojetos;

   ?>

<script type="text/javascript">

    $(document).ready(function() {
        load();    // put all your jQuery goodness in here.
    });

    function load()
    {
        var arreglo = new Array();
        var arreglonomes = new Array([],[]);
        var i=0;
        var k=0;
        <?php

        for($i=0;$i<count($nomeprojetos);$i++)
        {
            $valor = $nomeprojetos[$i]['valor'];
            $nome = $nomeprojetos[$i]['nome'];
        }

        // for para preencher as permissoes no arreglo javascript arreglo[i]
        $nro=count($result);
        for($i=0;$i<$nro;$i++)
        {
               ?>
             arreglo[i]= "<?php echo $result[$i]; ?>";
             i++; <?php }

        // for para preencher os nomes do projeto e seu valor no arreglo javascript arreglonomes[i]
        for($i=0;$i<count($nomeprojetos);$i++)
        {
               ?>
             arreglonomes[0][k]= "<?php echo $nomeprojetos[$i]['valor']; ?>";
             arreglonomes[1][k]= "<?php echo $nomeprojetos[$i]['nome']; ?>";
             k++; <?php }?>

        for(i=0;i<arreglonomes.length;i++)
        {
            agregar(arreglonomes[0][i], arreglonomes[1][i]);
        }


        var frm = document.getElementById("formu");

        for(i=0;i< arreglo.length; i++)
        {
             for (j=0;j<frm.elements.length;j++)
             {
                 if(frm.elements[j].type=='checkbox')
                 {
                     if(frm.elements[j].value == arreglo[i])
                     { frm.elements[j].checked=true;}
                 }
            }
        }
    }

    $(document).ready(function() {
        $('.fancybox').fancybox();
        $("#pesquisarprojetos").click(function() {
            $('<a class="fancybox fancybox.iframe" href="usuarios/fancyboxprojetos">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });

    function agregar($id,$nome){
        var branches = $("<li><input id='"+$id+"' name='datostree[]' type='checkbox' value='projetos|index|"+$id+"' checked >"+$nome+" <button type='button' onclick='apagar("+$id+")'>apagar</button><ul>" +
                "<li><input name='datostree[]' type='checkbox' id='proVi' value='projetos|detalhes|"+$id+"' >Visualizar</li>" +
                "<li><input name='datostree[]' type='checkbox' id='proAd' value='projetos|adicionar|"+$id+"' >Adicionar</li>" +
                "<li><input name='datostree[]' type='checkbox' id='proAl' value='projetos|adicionar|"+$id+"' >Alterar</li>" +
                "<li><input name='datostree[]' type='checkbox' id='proAp' value='projetos|excluir|"+$id+"' >Apagar</li></ul></li>").appendTo("#proj");
        $("#browser").treeview({
            add: branches
        });
    }

    function apagar($id){
        if ($("#"+$id+"").is("li") || $("#"+$id+"").parents("li").length) {
            $("#browser").treeview({
                remove: $("#"+$id+"").parents("li").filter(":first")
            });
            return false;
        }
    }

    $(function() {
        $("#browser").treeview();
        $("#browser1").treeview();
        $("#browser2").treeview();
        $("#browser3").treeview();
    })

</script>

<form name="formu" id="formu" action="<?php echo $this->url()?>" method="post">

    <div id="main">
        <ul id="browser" class="filetree">
            <li id="proj"><input name="datostree[]" type="checkbox" id="proAc" value="projetos|index|*">Projetos <button id="pesquisarprojetos" type="button">Adicionar</button></li>
        </ul>
    </div>

    <div id="main1">
        <ul id="browser1" class="filetree">

            <li><input name="datostree[]" type="checkbox" id="tarAc" value="tarefas|index|*">Tarefas
                <ul id="tarefas">
                    <li><input name="datostree[]" type="checkbox" id="tarVi" value="tarefas|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="tarAd" value="tarefas|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="tarAl" value="tarefas|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="tarAp" value="tarefas|excluir|*">Apagar</li>
                </ul>
            </li>

            <li><input  name="datostree[]" type="checkbox" id="arqAc" value="arquivos|index|*">Arquivos
                <ul id="arquivos">
                    <li><input name="datostree[]" type="checkbox" id="arqVi" value="arquivos|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="arqAd" value="arquivos|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="arqAl" value="arquivos|adicionar|*" ">Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="arqAp" value="arquivos|excluir|*" >Apagar</li>
                </ul>
            </li>
            <li><input  name="datostree[]" type="checkbox" id="benAc" value="beneficiarios|index|*">Beneficiario
                <ul id="beneficiarios">
                    <li><input name="datostree[]" type="checkbox" id="benVi" value="beneficiarios|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="benAd" value="beneficiarios|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="benAl" value="beneficiarios|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="benAp" value="beneficiarios|excluir|*" >Apagar</li>
                </ul>
            </li>
        </ul>
    </div>

    <div id="main2">
        <ul id="browser2" class="filetree">
            <li><input  name="datostree[]" type="checkbox" id="usuAc" value="usuarios|index|*">Usuario
                <ul id="usuarios">
                    <li><input name="datostree[]" type="checkbox" id="usuVi" value="usuarios|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="usuAd" value="usuarios|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="usuAl" value="usuarios|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="usuAp" value="usuarios|excluir|*" >Apagar</li>
                </ul>
            </li>
            <li><input  name="datostree[]" type="checkbox" id="empAc" value="empenhos|index|*">Empenho
                <ul id="empenhos">
                    <li><input name="datostree[]" type="checkbox" id="empVi" value="empenhos|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="empAd" value="empenhos|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="empAl" value="empenhos|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="empAp" value="empenhos|excluir|*" >Apagar</li>
                </ul>
            </li>
            <li><input  name="datostree[]" type="checkbox" id="insAc" value="instituicoes|index|*">Instituições
                <ul id="instituicoes">
                    <li><input name="datostree[]" type="checkbox" id="insVi" value="instituicoes|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="insAd" value="instituicoes|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="insAl" value="instituicoes|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="insAp" value="instituicoes|excluir|*" >Apagar</li>
                </ul>
            </li>
        </ul>
    </div>

    <div id="main3">
        <ul id="browser3" class="filetree">
            <li><input  name="datostree[]" type="checkbox" id="orcAc" value="orcamentario|index|*">Orçamento
                <ul id="orcamentario">
                    <li><input name="datostree[]" type="checkbox" id="orcVi" value="orcamentario|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="orcAd" value="orcamentario|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="orcAl" value="orcamentario|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="orcAp" value="orcamentario|excluir|*" >Apagar</li>
                </ul>
            </li>
            <li><input  name="datostree[]" type="checkbox" id="solAc" value="solicitacoes|index|*">Solicitações
                <ul id="solicitacoes">
                    <li><input name="datostree[]" type="checkbox" id="solVi" value="solicitacoes|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="solAd" value="solicitacoes|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="solAl" value="solicitacoes|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="solAp" value="solicitacoes|excluir|*" >Apagar</li>
                </ul>
            </li>
            <li><input  name="datostree[]" type="checkbox" id="tadAc" value="termoaditivo|index|*">Termo Aditivo
                <ul id="termoaditivo">
                    <li><input name="datostree[]" type="checkbox" id="tadVi" value="termoaditivo|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" id="tadAd" value="termoaditivo|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" id="tadAl" value="termoaditivo|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" id="tadAp" value="termoaditivo|excluir|*" >Apagar</li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="but">

        <input type="submit" value="Submit">
    </div>
</form>





