<script type="text/javascript">
    $(document).ready(function() {
        $('.fancybox').fancybox();
        $("#pesquisarprojetos").click(function() {
            $('<a class="fancybox fancybox.iframe" href="usuarios/fancyboxprojetos">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });

    function agregar($id,$nome){
        var branches = $("<li><input id='"+$id+"' name='datostree[]' type='checkbox' value='projetos|index|"+$id+"' checked >"+$nome+" <button onclick='apagar("+$id+")'>apagar</button><ul>" +
                "<li><input name='datostree[]' type='checkbox' value='projetos|detalhes|"+$id+"' >Visualizar</li>" +
                "<li><input name='datostree[]' type='checkbox' value='projetos|adicionar|"+$id+"' >Adicionar</li>" +
                "<li><input name='datostree[]' type='checkbox' value='projetos|adicionar|"+$id+"' >Alterar</li>" +
                "<li><input name='datostree[]' type='checkbox' value='projetos|excluir|"+$id+"' >Apagar</li></ul></li>").appendTo("#proj");
        $("#browser").treeview({
            add: branches
        });
    }

    function apagar($id){
        if ($("#"+$id+"").is("li") || $("#"+$id+"").parents("li").length) {
            $("#browser").treeview({
                remove: $("#"+$id+"").parents("li").filter(":first")
            });
            return false;
        }
    }

    $(function() {
        $("#browser").treeview();
    })

</script>

<form action="<?php echo $this->url() ?>" method="POST">

    <div id="main">
        <ul id="browser" class="filetree">
            <li id="proj"><input name="datostree[]" type="checkbox" value="projetos|index|*">Projetos <button id="pesquisarprojetos" type="button">Adicionar</button></li>

            <li><input name="datostree[]" type="checkbox" value="tarefas|index|*">Tarefas1
                <ul id="tarefas">
                    <li><input name="datostree[]" type="checkbox" value="tarefas|detalhes|*" >Visualizar</li>
                    <li><input name="datostree[]" type="checkbox" value="tarefas|adicionar|*" >Adicionar</li>
                    <li><input name="datostree[]" type="checkbox" value="tarefas|adicionar|*" >Alterar</li>
                    <li><input name="datostree[]" type="checkbox" value="tarefas|excluir|*" >Apagar</li>
                </ul>
            </li>
        </ul>
    </div>

    <input type="submit" value="Submit">

</form>





