<script type="text/javascript" src="js/jquery.ui.combogrid-1.6.2.js"></script>
<script type="text/javascript">
    /*$(document).ready(function(){
        var pid = $("#desembolso-projeto_id").val();
        $( "#desembolso-empenho").combogrid({
            debug:false,
            colModel: [{'columnName':'nome','width':'45','label':'Beneficiário'},{'columnName':'descricao_historico','width':'55','label':'Descrição'}],
            url: 'desembolso/combogridempenho/projeto_id/'+pid,
            select: function( event, ui ) {
                $("#desembolso-empenho").val( ui.item.nome + ' - ' +  ui.item.descricao_historico );
                return false;
            }
        });
    });   */

    function saldoEmpenho(id) {
        $.ajax({
            url: '/desembolso/saldoempenho/empenho_id/'+id,
            dataType:'html',
            type:'GET',
            success: function(data){
                $('#desembolso-saldo_empenho').val(data);
                var saldo_financeiro = $('#desembolso-saldo_financeiro').val();
                saldo_financeiro = parseFloat(saldo_financeiro);
                data = parseFloat(data);
                // $form->getInputFilter()->get('element_name')->getValidatorChain()->attach(new ValidatorClassName());
                if (saldo_financeiro > data)
                {
                    $('#desembolso-valor_desembolso').attr('validators', array("Zend_Validate_Between2(array('min' => '0,00', 'max' => " + saldo_financeiro + ")"))
                }
                else
                {
                    $('#desembolso-valor_desembolso').attr('validators', array("Zend_Validate_Between2(array('min' => '0,00', 'max' => " + data + ")"))
                }
            }
        })
    }

    function maskPre(val, msk, pre) {

        val = val.replace(RegExp('[' + msk.replace(/#/g, '') + ']', 'g'), '')

        if (val.length > 0) {
            val = pre + val
        }

        mskVal = ''
        v = val.length - 1
        for (m = msk.length - 1; m >= 0 && v >= -msk.indexOf('#'); --m) {
            if ('#' != msk.charAt(m)) {
                mskVal = msk.charAt(m) + mskVal
                if ('#' != msk.charAt(m - 1))
                    continue
                --m
            }
            mskVal = val.charAt(v) + mskVal
            v--

        }

        if (pre.length > 0) {
            mskVal = mskVal.replace(RegExp('^' + pre.charAt(0) + '+', 'g'), '')
        }

        return mskVal

    }

    function mask(val, msk) {

        return maskPre(val, msk, '')
    }
</script>

<style>
    table * *{
        text-align: center;
    }
</style>

<?php
    $this->form->setAction($this->url());
    echo $this->form;

$somaDespesasCorrentes = 0;
$somaDespesasCapitais = 0;
$somaDesembolso = 0;
$datefilter = new Zend_Filter_DateFilter();
$decimalfilter = new Zend_Filter_DecimalFilter();

//$somaDespesasCorrentes = number_format(0 + $this->somaRubricas[0], 2, '.', '');
//$somaDespesasCapitais = number_format(0 + $this->somaRubricas[1], 2, '.', '');
$somaDesembolso = number_format(0 + $this->soma[0]['SUM( d.valor_desembolso )'], 2, '.', '');
$somaSaldoFin =  number_format(0 + ($this->soma[0]['valor_recebido'] - $somaDesembolso), 2, '.', '');

echo "</br>";
echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
echo "<thead style='background-color: #E2E4FF;'>";
echo "<tr>";
echo "<th> Total Desembolsado</th>";
echo "<th> Saldo Financeiro</th>";
echo "</tr>";
echo "</thead>";

echo "<tbody style='color:green;'>";
echo "<tr>";
//echo "<td>" . $decimalfilter->filter($somaDespesasCorrentes) . "</td>";
//echo "<td>" . $decimalfilter->filter($somaDespesasCapitais) . "</td>";
echo "<td>" . $decimalfilter->filter($somaDesembolso) . "</td>";
echo "<td>" . $decimalfilter->filter($somaSaldoFin) . "</td>";

echo "</tr>";
echo "</tbody>";
echo "</table>";
echo "</br></br></br>";
?>