<script type="text/javascript" src="js/jquery.ui.combogrid-1.6.2.js"></script>
<script type="text/javascript">
    /*$(document).ready(function(){
        var pid = $("#desembolso-projeto_id").val();
        $( "#desembolso-empenho").combogrid({
            debug:false,
            colModel: [{'columnName':'nome','width':'45','label':'Beneficiário'},{'columnName':'descricao_historico','width':'55','label':'Descrição'}],
            url: 'desembolso/combogridempenho/projeto_id/'+pid,
            select: function( event, ui ) {
                $("#desembolso-empenho").val( ui.item.nome + ' - ' +  ui.item.descricao_historico );
                return false;
            }
        });
    });   */

function maskPre(val, msk, pre) {

        val = val.replace(RegExp('[' + msk.replace(/#/g, '') + ']', 'g'), '')

        if (val.length > 0) {
            val = pre + val
        }

        mskVal = ''
        v = val.length - 1
        for (m = msk.length - 1; m >= 0 && v >= -msk.indexOf('#'); --m) {
            if ('#' != msk.charAt(m)) {
                mskVal = msk.charAt(m) + mskVal
                if ('#' != msk.charAt(m - 1))
                    continue
                --m
            }
            mskVal = val.charAt(v) + mskVal
            v--

        }

        if (pre.length > 0) {
            mskVal = mskVal.replace(RegExp('^' + pre.charAt(0) + '+', 'g'), '')
        }

        return mskVal

    }
    
    function mask(val, msk) {

        return maskPre(val, msk, '')
    }
</script>

<?php
    $this->form->setAction($this->url());
    echo $this->form;
?>