<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExtorno(id)
    {
        var answer = confirm("Deseja realmente extornar o desembolso?");
        if (answer) {
            top.location.href = '/../desembolso/extornar/desembolso_id/'+id;
        }
        else {
            alert("O desembolso não foi extornado!");
        }
    }
</script>

<?php
 $id = $this->id;

echo "<button onclick='confirmarExtorno($id)'>Extornar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>