<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/<?php echo $projeto_id; ?>">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });

</script>

<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExtorno(id, pid)
    {
        var answer = confirm("Deseja realmente extornar o desembolso?");
        if (answer) {
            top.location.href = '/../desembolso/extornar/desembolso_id/'+id+ '/projeto_id/'+pid;
        }
        else {
            alert("O desembolso não foi extornado!");
        }
    }
</script>

<?php
 $id = $this->id;

echo "<button onclick='confirmarExtorno($id, $projeto_id)'>Extornar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>