<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
           // "bProcessing": true,
           // "sAjaxSource": 'desembolso/indexajax'
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/'+<?php echo $projeto_id; ?>+'">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../desembolso/adicionar/projeto_id/'+projeto_id;

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novodesembolso {
        float:right;
    }
</style>

<?php
    echo "<button class='menu_financeiro'>Menu Financeiro</button>";
    echo "<button class='novodesembolso btn_add' onclick='adicionar($projeto_id)'>Novo Desembolso</button>";

?>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Código</th>
        <th>Natureza da Despesa</th>
        <th>Processo Administrativo</th>
        <th>Histórico</th>
        <th>Código do Documento Hábil</th>
        <th>Data do Documento</th>
        <th>Ordem Bancária</th>
        <th>Data do Pagamento</th>
        <th>Valor</th>
    </tr>
    </thead>
    <tbody>

    <?php

    $somaRubrica = 0;
    $somaEmpenho = 0;
    $somaSaldoOrc = 0;
    $somaDesembolso = 0;
    $datefilter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();


    $orcamentoProjeto = $decimalfilter->filter($this->orcamentoProjeto[0]['orcamento']);
    $somaEmpenho = number_format(0 + ($this->soma[0]['valor_empenho'] + $this->soma[0]['valor_pre_empenho']), 2, '.', '');
    $somaOrcamentoDisponiblizado = number_format(0 + ($this->soma[0]['valor']), 2, '.', '');
    $somaDesembolso = number_format(0 + $this->soma[0]['SUM( d.valor_desembolso )'], 2, '.', '');
    $somaRubrica = number_format(0 + $this->soma[0]['valor_orcamento'], 2, '.', '');
    $somaSaldoFin =  number_format(0 + ($this->soma[0]['valor_recebido'] - $somaDesembolso), 2, '.', '');

    foreach($this->resultado as $row)
    {

        echo "<tr id='".$row['desembolso_id']."'>";
        echo "<td>" . $row['codigo_rubrica'] . "</td>";
        echo "<td>" . $row['descricao'] . "</td>";
        echo "<td>" .   $row['processo_administrativo'] . "</td>";
        echo "<td>" .   $row['descricao_historico'] . "</td>";
        echo "<td ><a href='/desembolso/detalhes/desembolso_id/{$row['desembolso_id']}/projeto_id/$projeto_id'>" .  $row['codigo_documento_habil'] . "</td>";
        echo "<td >" .  $datefilter->filter($row['data_documento_habil']) . "</td>";
        echo "<td >" .  $row['order_dinheiro'] . "</td>";
        echo "<td >" .  $datefilter->filter($row['data_pagamento']) . "</td>";
        echo "<td >" .  $decimalfilter->filter($row['valor_desembolso']) . "</td>";

        echo "</tr>";
    }
    echo "</tbody></table>";

    echo "</br>";
    echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
    echo "<thead style='background-color: #E2E4FF;'>";
    echo "<tr>";
    echo "<th> Orçamento Previsto</th>";
    echo "<th> Total Rubrica</th>";
    echo "<th> Orçamento Disponibilizado</th>";
    echo "<th> Total Empenhado</th>";
    echo "<th> Saldo Orçamentário</th>";
    echo "<th> Total Desembolsado</th>";
    echo "<th> Saldo Financeiro</th>";
    echo "</tr>";
    echo "</thead>";

    echo "<tbody style='color:green;'>";
    echo "<tr>";
    echo "<td>" . $orcamentoProjeto . "</td>";
    echo "<td>" . $decimalfilter->filter($somaRubrica) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaOrcamentoDisponiblizado) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaEmpenho) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaOrcamentoDisponiblizado - $somaEmpenho) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaDesembolso) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaSaldoFin) . "</td>";

    echo "</tr>";
    echo "</tbody>";
    echo "</table>";
    echo "</br></br></br>";
?>