<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
           // "bProcessing": true,
           // "sAjaxSource": 'desembolso/indexajax'
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../desembolso/adicionar/projeto_id/'+projeto_id;

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novodesembolso {
        float:right;
    }
</style>

<?php
    $projeto_id = $this->id;
    echo "<button class='novodesembolso btn_add' onclick='adicionar($projeto_id)'>Novo Desembolso</button>";

?>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Id</th>
        <th>Desembolso_Rel</th>
        <th>Empenho</th>
        <th>Código do Documento Hábil</th>
        <th>Data do Documento</th>
        <th>Ordem Bancária</th>
        <th>Data do Pagamento</th>
        <th>Valor</th>
        <th>Extornado</th>
    </tr>
    </thead>
    <tbody>

    <?php

    $datefilter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();

    foreach($this->resultado as $row)
    {
        echo "<tr id='".$row['desembolso_id']."'>";
        echo "<td><a href='/desembolso/detalhes/desembolso_id/{$row['desembolso_id']}'>" .   $row['desembolso_id'] . "</td>";
        echo "<td>" .   $row['desembolso_rel'] . "</td>";
        echo "<td><a href='/empenhos/detalhes/empenho_id/{$row['empenho_id']}'>" .   $row['empenho_id'] . "</td>";
        echo "<td >" .  $row['codigo_documento_habil'] . "</td>";
        echo "<td >" .  $datefilter->filter($row['data_documento_habil']) . "</td>";
        echo "<td >" .  $row['order_dinheiro'] . "</td>";
        echo "<td >" .  $datefilter->filter($row['data_pagamento']) . "</td>";
        echo "<td >" .  $decimalfilter->filter($row['valor_desembolso']) . "</td>";

        if ($row['extornado'] == true)
        {
            echo "<td> Sim </td>";
        }
        else
        {
            echo "<td> Não </td>";
        }
        //echo "<td >" .  $row['extornado'] . "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>