<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/<?php echo $projeto_id; ?>">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });

</script>

<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id, pid)
    {
        var answer = confirm("Deseja realmente excluir o cronograma?");
        if (answer) {
            top.location.href = '/../cronogramaorcamentario/excluir/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;
        }
        else {
            alert("O cronograma não foi excluído!");
        }
    }
</script>
<script>
    function editar(id, pid)
    {
        top.location.href = '/../cronogramaorcamentario/adicionar/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;

    }
</script>

<?php
 $id = $this->id;
$pid = $this->pid;

echo "<button class=\"right btn_delete\" onclick='confirmarExclusao($id, $pid)'>Excluir</button>";
echo "<button class=\"right btn_edit\" onclick='editar($id, $pid)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>
