<?php
$projeto_id = $this->pid;
?>

<style>
    body { font-size: 62.5%; }
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>

<div id="dialog-form" title="Receber valor">
  <p class="validateTips">Preencha todos os campos.</p>
 
  <form>
  <fieldset>
    <label for="date">Data de recebimento:</label>
    <input type="text" name="date" id="date" class="text ui-widget-content ui-corner-all " />
    <label for="valor">Valor:</label>
    <input type="text" name="valor" id="valor" value="" class="text ui-widget-content ui-corner-all" maxlength="13" onkeyup="this.value=mask(this.value, '###.###.###,##')" />
  </fieldset>
  </form>
</div>
 
<script>
    var pid, id_crono;
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/'+<?php echo $projeto_id; ?>+'">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
        
        $("#date").datepicker({"dateFormat":"dd\/mm\/yy","dayNamesMin":["D","S","T","Q","Q","S","S"],"monthNames":["Janeiro","Fevereiro","Mar\u00e7o","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]});
    });
    
    function maskPre(val, msk, pre) {

        val = val.replace(RegExp('[' + msk.replace(/#/g, '') + ']', 'g'), '')

        if (val.length > 0) {
            val = pre + val
        }

        mskVal = ''
        v = val.length - 1
        for (m = msk.length - 1; m >= 0 && v >= -msk.indexOf('#'); --m) {
            if ('#' != msk.charAt(m)) {
                mskVal = msk.charAt(m) + mskVal
                if ('#' != msk.charAt(m - 1))
                    continue
                --m
            }
            mskVal = val.charAt(v) + mskVal
            v--

        }

        if (pre.length > 0) {
            mskVal = mskVal.replace(RegExp('^' + pre.charAt(0) + '+', 'g'), '')
        }

        return mskVal

    }
    
    function mask(val, msk) {

        return maskPre(val, msk, '')
    }
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../cronogramaorcamentario/adicionar/projeto_id/'+projeto_id;

    }

    function editar(id, pid)
    {
        top.location.href = '/../cronogramaorcamentario/adicionar/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;
    }
    
    function receber(date, valor, id, pid)
    {
        if (confirm("O valor previsto será transformado em valor recebido. Confirmar?")) {
            if(date == "" || valor == "") {
                alert("Preencha todos os campos!");
                return;
            }
            date = date.split("/")[2]+"-"+date.split("/")[1]+"-"+date.split("/")[0];
            top.location.href = '/../cronogramaorcamentario/receber/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid+'/date/'+date+'/valor/'+valor;
            
            //alert( '/../cronogramafinanceiro/receber/cronograma_financeiro_id/'+id+'/projeto_id/'+pid+'/date/'+date+'/valor/'+valor);
        }
    }
    
    function distribuir(id, pid, saldo)
    {
        top.location.href = '/../cronogramaorcamentario/distribuir/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid+'/saldo/'+saldo;
    }

    function confirmarExclusao(id, pid)
    {
        var answer = confirm("Deseja realmente excluir o cronograma?");
        if (answer) {
            top.location.href = '/../cronogramaorcamentario/excluir/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;
        }
        else {
            alert("O cronograma não foi excluído!");
        }
    }

</script>
<style>
    table * *{
        text-align: center;
    }
    .novaparcela {
        float:right;
    }
</style>
<?php
    echo "<button class='menu_financeiro'>Menu Financeiro</button>";
    echo "<button class='novaparcela btn_add' onclick='adicionar($projeto_id)'>Nova Parcela</button>";
?>
<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Parcela</th>
        <th>Data</th>
        <th>Orçamento a receber</th>
        <th>Orçamento disponibilizado</th>
        <th>Orçamento utilizado</th>
        <th>Data do pagamento</th>
        <th>Tipo</th>
        <th>Fatura</th>
        <th>Receber valor</th>
        <th>Distribuir valor</th>
        <th>Editar</th>
        <th>Excluir</th>
<!--        <th>Data final real</th>-->
<!--        <th>Estado do projeto</th>-->
<!--        <th>Porcentagem completa</th>-->
<!--        <th>Prioridade</th>-->
<!--        <th>Coordenador técnico</th>-->
    </tr>
    </thead>
    <tbody>

    <?php

    $filter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();
    $datefilter = new Zend_Filter_DateFilter();
    $i = 1;
    $pagas = 0;
    $totalPrevisto = $this->total[0]['SUM( c.valor_a_receber )'];
    $totalRecebido = $this->total[0]['SUM( c.valor_recebido )'];
    foreach($this->cronograma_orcamentario as $row)
    {
       $disabled = "";
       $sub_saldo = $row['valor_recebido'] - $row['orcamento_utilizado'];
       if ($sub_saldo <= 0) {
           $disabled = "disabled='disabled'";
       }
    //$row = $row->toArray();
    echo "<tr id='".$row['cronograma_orcamentario_id']."'>";
    echo "<td>" .$i. "</td>";
    echo "<td>" .   $datefilter->filter($row['data_previa']) . "</td>";
    echo "<td>" .   $decimalfilter->filter($row['valor_a_receber']) . "</td>";
    echo "<td><a href='/cronogramaorcamentario/detalhes/cronograma_orcamentario_id/{$row['cronograma_orcamentario_id']}/projeto_id/{$projeto_id}'>"
        .$decimalfilter->filter($row['valor_recebido']) . "</a></td>";
    echo "<td>" .   $decimalfilter->filter($row['orcamento_utilizado']) . "</td>";
    echo "<td>" .   $datefilter->filter($row['data_pagamento']) . "</td>";
    echo "<td>" .   $row['tipo'] . "</td>";
    echo "<td>" .   $row['numero_fatura_pf'] . "</td>";
//    echo "<td><a class='\right btn_edit\' href='/cronogramaorcamentario/adicionar/projeto_id/".$projeto_id."/cronograma_orcamentario_id/"
//    ."{$row['cronograma_orcamentario_id']}'>aa</a></td>";
//    echo "<td><a class='\right btn_delete\' href='/cronogramaorcamentario/excluir/cronograma_orcamentario_id/{$row['cronograma_orcamentario_id']}'>bb</a></td>";
    //echo "<td><button class=\"center btn_receive\" onclick='receber(".$row['cronograma_orcamentario_id'].", ".$projeto_id.")'>Receber</button>";
    echo "<td><button id=\"create-user". $i."\" class=\"create-user\" onclick=\"pid = ".$projeto_id."; id_crono = ".$row['cronograma_orcamentario_id'].";\">Receber</button>";
    echo "<td><button onclick=\"distribuir(".$row['cronograma_orcamentario_id'].", ".$projeto_id.", '".base64_encode($sub_saldo)."')\" $disabled>Distribuir valor</button>";
    echo "<td><button class=\"center btn_edit\" onclick='editar(".$row['cronograma_orcamentario_id'].", ".$projeto_id.")'>Editar</button>";
    echo "<td><button class=\"center btn_delete\" onclick='confirmarExclusao(".$row['cronograma_orcamentario_id'].", ".$projeto_id.")'>Excluir</button>";
    $i++;

    if ($row['valor_a_receber'] == 0)
    {
        $pagas++;

    }

    echo "</tr>";
    }
    echo "</tbody></table>";

    echo "</br>";
    echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
    echo "<thead style='background-color: #E2E4FF;'>";
    echo "<tr>";
    echo "<th> Total Rubricas</th>";
    echo "<th> Valor Total a Receber</th>";
    echo "<th> Valor Total Recebido</th>";
    echo "<th> Índice de Realização das Parcelas</th>";
    echo "</tr>";
    echo "</thead>";

    echo "<tbody style='color:green;'>";
    echo "<tr>";
    echo "<td>" . $decimalfilter->filter(number_format(0 + $this->totalRubricas[0]['valor_orcamento'], 2, '.', '')) . "</td>";
    echo "<td>" . $decimalfilter->filter(number_format(0 + $totalPrevisto, 2, '.', '')) . "</td>";
    echo "<td>" . $decimalfilter->filter(number_format(0 + $totalRecebido, 2, '.', '')) . "</td>";
    if ($i = 1)
    {
        echo "<td>" . number_format(0, 2, '.', '') . "%</td>";
    }
    else
    {
        echo "<td>" . number_format(0 + ($pagas/($i - 1)) * 100, 2, '.', '') . "%</td>";
    }

    echo "</tr>";
    echo "</tbody>";
    echo "</table>";
    echo "</br></br></br>";
?>