<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/'+<?php echo $projeto_id; ?>+'">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../cronogramaorcamentario/adicionar/projeto_id/'+projeto_id;

    }

    function editar(id, pid)
    {
        top.location.href = '/../cronogramaorcamentario/adicionar/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;
    }

    function receber(id, pid)
    {
        if (confirm("O valor previsto será transformado em valor recebido. Confirmar?")) {
            top.location.href = '/../cronogramaorcamentario/receber/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;
        }
    }

    function confirmarExclusao(id, pid)
    {
        var answer = confirm("Deseja realmente excluir o cronograma?");
        if (answer) {
            top.location.href = '/../cronogramaorcamentario/excluir/cronograma_orcamentario_id/'+id+'/projeto_id/'+pid;
        }
        else {
            alert("O cronograma não foi excluído!");
        }
    }

</script>
<style>
    table * *{
        text-align: center;
    }
    .novaparcela {
        float:right;
    }
</style>
<?php
    echo "<button class='menu_financeiro'>Menu Financeiro</button>";
    echo "<button class='novaparcela btn_add' onclick='adicionar($projeto_id)'>Nova Parcela</button>";
?>
<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Parcela</th>
        <th>Data</th>
        <th>Orçamento a receber</th>
        <th>Orçamento disponibilizado</th>
        <th>Tipo</th>
        <th>Fatura</th>
        <th>Receber valor</th>
        <th>Editar</th>
        <th>Excluir</th>
<!--        <th>Data final real</th>-->
<!--        <th>Estado do projeto</th>-->
<!--        <th>Porcentagem completa</th>-->
<!--        <th>Prioridade</th>-->
<!--        <th>Coordenador técnico</th>-->
    </tr>
    </thead>
    <tbody>

    <?php

    $filter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();
    $i = 1;
    $pagas = 0;
    $totalPrevisto = $decimalfilter->filter($this->total[0]['SUM( c.valor_a_receber )']);
    $totalRecebido = $decimalfilter->filter($this->total[0]['SUM( c.valor_recebido )']);
    foreach($this->cronograma_orcamentario as $row)
    {
    //$row = $row->toArray();
    echo "<tr id='".$row['cronograma_orcamentario_id']."'>";
    echo "<td>" .$i. "</td>";
    echo "<td>" .   $row['data_previa'] . "</td>";
    echo "<td>" .   $decimalfilter->filter($row['valor_a_receber']) . "</td>";
    echo "<td><a href='/cronogramaorcamentario/detalhes/cronograma_orcamentario_id/{$row['cronograma_orcamentario_id']}/projeto_id/{$projeto_id}'>"
        .$decimalfilter->filter($row['valor_recebido']) . "</a></td>";
    echo "<td>" .   $row['tipo'] . "</td>";
    echo "<td>" .   $row['numero_fatura_pf'] . "</td>";
//    echo "<td><a class='\right btn_edit\' href='/cronogramaorcamentario/adicionar/projeto_id/".$projeto_id."/cronograma_orcamentario_id/"
//    ."{$row['cronograma_orcamentario_id']}'>aa</a></td>";
//    echo "<td><a class='\right btn_delete\' href='/cronogramaorcamentario/excluir/cronograma_orcamentario_id/{$row['cronograma_orcamentario_id']}'>bb</a></td>";
    echo "<td><button class=\"center btn_receive\" onclick='receber(".$row['cronograma_orcamentario_id'].", ".$projeto_id.")'>Receber</button>";
    echo "<td><button class=\"center btn_edit\" onclick='editar(".$row['cronograma_orcamentario_id'].", ".$projeto_id.")'>Editar</button>";
    echo "<td><button class=\"center btn_delete\" onclick='confirmarExclusao(".$row['cronograma_orcamentario_id'].", ".$projeto_id.")'>Editar</button>";
    $i++;

    if ($row['valor_a_receber'] == 0)
    {
        $pagas++;

    }

    echo "</tr>";
    }
    echo "</tbody></table>";

    echo "</br>";
    echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
    echo "<thead style='background-color: #E2E4FF;'>";
    echo "<tr>";
    echo "<th> Total Rubricas</th>";
    echo "<th> Valor Total a Receber</th>";
    echo "<th> Valor Total Recebido</th>";
    echo "<th> Índice de Realização das Parcelas</th>";
    echo "</tr>";
    echo "</thead>";

    echo "<tbody style='color:green;'>";
    echo "<tr>";
    echo "<td>" . $decimalfilter->filter($this->totalRubricas[0]['valor_orcamento']) . "</td>";
    echo "<td>" . $decimalfilter->filter($totalPrevisto) . "</td>";
    echo "<td>" . $decimalfilter->filter($totalRecebido) . "</td>";
    echo "<td>" . number_format(0 + ($pagas/($i - 1)) * 100, 2, '.', '') . "%</td>";

    echo "</tr>";
    echo "</tbody>";
    echo "</table>";
    echo "</br></br></br>";
?>