<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function prorrogar()
    {
        top.location.href = '/../termoaditivo/prorrogar/';

    }
    function remanejar()
    {
        top.location.href = '/../termoaditivo/remanejar/';

    }
    function alterar()
    {
        top.location.href = '/../termoaditivo/alterar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .alterar, .remanejar, .prorrogar {
        float:right;
    }
</style>
<button class='alterar' onclick='alterar()'>Alterar</button>
<button class='remanejar' onclick='remanejar()'>Remanejar</button>
<button class='prorrogar' onclick='prorrogar()'>Prorrogar</button>


<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Id</th>
        <th>Data</th>
        <th>Descrição</th>
        <th>Usuário</th>
    </tr>
    </thead>
    <tbody>

    <?php
    foreach($this->termoaditivo as $row)
    {
    //$row = $row->toArray();
    echo "<tr id='".$row['termo_aditivo_id']."'>";
    echo "<td>" .   $row['termo_aditivo_id'] . "</td>";
    echo "<td>" .   $row['data_modificacao'] . "</td>";
    echo "<td>" .   $row['descricao_justificativa'] . "</td>";
    echo "<td >" .  $row['u.username'] . "</td>";
    echo "</tr>";
    }
    echo "</tbody></table>";
?>