<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function prorrogar(projeto_id)
    {
        top.location.href = '/../termoaditivo/prorrogar/projeto_id/'+projeto_id;

    }
    function remanejar(projeto_id)
    {
        top.location.href = '/../termoaditivo/remanejar/projeto_id/'+projeto_id;

    }
    function alterar(projeto_id)
    {
        top.location.href = '/../termoaditivo/alterar/projeto_id/'+projeto_id;

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .alterar, .remanejar, .prorrogar {
        float:right;
    }
</style>
<?php
$projeto_id = $this->id;
echo "<button class='alterar' onclick='alterar($projeto_id)'>Alterar</button>";
echo "<button class='remanejar' onclick='remanejar($projeto_id)'>Remanejar</button>";
echo "<button class='prorrogar' onclick='prorrogar($projeto_id)'>Prorrogar</button>";
?>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Id</th>
        <!-- <th>Projeto Alterado</th> -->
        <th>Data</th>
        <th>Tipo de Modificação</th>
        <th>Ação</th>
        <th>Descrição/Motivo</th>
        <th>Usuário</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $filter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();
    foreach($this->termoaditivo as $row)
    {
    //$row = $row->toArray();
    echo "<tr id='".$row['termo_aditivo_id']."'>";
    echo "<td>" .   $row['termo_aditivo_id'] . "</td>";
    //echo "<td>" .   $row['p.projeto_id'] . " - " . $row['p.nome'] . "</td>";
    echo "<td>" .   $row['data_termo_aditivo'] . "</td>";
    echo "<td>" .   $row['tp.nome_tipo'] . "</td>";
    if ($row['tp.nome_tipo'] == 'Prorrogação')
    {
        echo "<td> Data final alterada de " . $filter->filter($row['data_fim_atual']) . " para " . $filter->filter($row['data_fim_nova']) . "</td>";
    }
    else if ($row['tp.nome_tipo'] == 'Remanejamento')
    {
        echo "<td> Foram remanejados R$" . $decimalfilter->filter($row['valor_termino_aditivo']) . " da rubrica " . $row['r.codigo_rubrica'] . "->" . $row['r.descricao']
            . " para " . $row['rr.codigo_rubrica'] . "->" . $row['rr.descricao'] . "</td>";
    }
    else
    {
        echo "<td> Foi alterado o valor da rubrica " . $row['rr.codigo_rubrica'] . "->" . $row['rr.descricao'] . " para R$" . $row['valor_termino_aditivo'] . "</td>";
    }
    echo "<td>" .   $row['termo_aditivo_descricao'] . "</td>";
    echo "<td >" .  $row['u.username'] . "</td>";
    echo "</tr>";
    }
    echo "</tbody></table>";
?>