<!--<script type="text/javascript" src="js/jquery.ui.combogrid-1.6.2.js"></script>-->
<!--<script type="text/javascript">-->
<!--    $(document).ready(function(){-->
<!--        $( "#solicitacoes-projeto").combogrid({-->
<!--            debug:false,-->
<!--            colModel: [{'columnName':'apelido','width':'45','label':'Apelido'},{'columnName':'nome','width':'45','label':'Nome'}],-->
<!--            url: 'solicitacoes/combogridprojeto/',-->
<!--            select: function( event, ui ) {-->
<!--                $("#solicitacoes-projeto").val( ui.item.apelido + ' - ' +  ui.item.nome );-->
<!--                $("#solicitacoes-projeto_id").val( ui.item.projeto_id );-->
<!--                $('#solicitacoes-coordenador_tecnico_id').val(ui.item.coordenador_tecnico);-->
<!--                preencher();-->
<!--                return false;-->
<!--            }-->
<!--        });-->
<!--    });-->
<!---->
<!--</script>-->

<?php
$this->form->setAction($this->url());
$form = $this->form;
echo $this->form;
?>

<script>

    var local = '';
    function tipoLocal(valor){
        valor=$('#solicitacoes-local').is(':checked');
        if (valor == false){
            $('#solicitacoes-local_entrega_solicitacao_view').attr('disabled', 'disabled');
            $('#solicitacoes-local_entrega_solicitacao_view').attr('value', 'CDT');
            $('#solicitacoes-local_entrega_solicitacao').attr('value', 'CDT');

        }else
        {
            $('#solicitacoes-local_entrega_solicitacao_view').removeAttr('disabled');

        }
    }

    function setLocal(valor){
        local = valor;
        $('#solicitacoes-local_entrega_solicitacao').attr('value', valor);
    }

    function getLocal() {
        return local;
    }

    function getItemId(){
        return 'nada';
    }

    function setSaldoOrcamento(saldo)
    {
        alert(saldo);
    }

    function calcularTotal(index)
    {
        //var quantidade = $('#solicitacoes').getElementsByName('solicitacoes[numero_itens_'+index+']');
        var ind1 = 4*(index-1)+1;
        var ind2 = 4*(index-1)+3;
        var ind3 = 4*(index-1)+4;

        var numItens = $('div#descricao dd').eq(ind1-1);
        var x = numItens.children('input').val();
        var quantidade = parseFloat(x);
        var precoUnitario = $('div#descricao dd').eq(ind2-1);
        var y = precoUnitario.children('input').val();
        var valor = parseFloat(y);
        var total = quantidade * valor;
        //$('#solicitacoes-valor_estimado').nth(2).attr('value', total);
        var valorEstimado = $('div#descricao dd').eq(ind3-1);
        valorEstimado.children('input').attr('value', total);

    }

    function preencher()
    {
        var valor = 'id=' + $('#solicitacoes-coordenador_tecnico_id').val();
        $.ajax({
            url: '/solicitacoes/preenchecoordenador/',
            dataType:'json',
            data: valor,
            success: function(data){
                $('#solicitacoes-coordenador_projeto').val(data.username);
                $('#solicitacoes-email').val(data.email);
                $('#solicitacoes-telefone_coordenador').val(data.telefone);
                $('#solicitacoes-celular_coordenador').val(data.celular);

            }
        })
    }

</script>