

<script>

    $(function($){
        // ADICIONAR TAREFAS
        $('#empenhos-botao_Adicionar_Tarefa').click(function(){
            $('#empenhos-tarefas option:selected').clone().prependTo($('#empenhos-tarefa_empenho'));
            $('#empenhos-tarefas option:selected').remove();
        });

        // REMOVE TAREFAS
        $('#empenhos-botao_Deletar_Tarefa').click(function(){
            $('#empenhos-tarefa_empenho option:selected').clone().prependTo($('#empenhos-tarefas'));
            $('#empenhos-tarefa_empenho option:selected').remove();
        });

        //seleciona as tarefas para serem envidas ao controller
        $('#empenhos-submit').click(function(){
            $('#empenhos-tarefa_empenho > option').each(
                    function(){
                        $(this).prop('selected', true);
                    });
        });
    })
</script>

<?php
$id = $this->id;
$tipo = $this->tipo;
$projeto_id = $this->pid;

echo "<button onclick='aprovar($id, $tipo, $projeto_id)'>Aprovar Pre-Empenho</button>";

$this->detalhespreempenho->setAction($this->url());
echo $this->detalhespreempenho;

?>
