<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id, tipo, projeto_id)
    {
        if (tipo == 1 || tipo == 4 || tipo == 5)
        {
            var answer = confirm("Deseja realmente excluir a solicitação?");
            if (answer)
            {
                top.location.href = '/../solicitacoes/excluiraquisicao/solicitacao_id/'+id+'/projeto_id/'+projeto_id;
            }
            else
            {
            alert("A solicitação não foi excluída!");
            }
        }
        else if (tipo == 2 || tipo == 6 || tipo == 7 || tipo == 8)
        {
            var answer = confirm("Deseja realmente excluir a solicitação?");
            if (answer)
            {
                top.location.href = '/../solicitacoes/excluircontratacao/solicitacao_id/'+id+'/projeto_id/'+projeto_id;
            }
            else
            {
                alert("A solicitação não foi excluída!");
            }
        }
        else
        {
            var answer = confirm("Deseja realmente excluir a solicitação?");
            if (answer)
            {
                top.location.href = '/../solicitacoes/excluirpassagens/solicitacao_id/'+id+'/projeto_id/'+projeto_id;
            }
            else
            {
                alert("A solicitação não foi excluída!");
            }
        }

    }
</script>
<script>
    function editar(id, tipo, projeto_id)
    {
        if (tipo == 1 || tipo == 4 || tipo == 5)
        {
        top.location.href = '/../solicitacoes/adicionaraquisicao/solicitacao_id/'+id+'/projeto_id/'+projeto_id;
        }
        else if (tipo == 2 || tipo == 6 || tipo == 7 || tipo == 8)
        {
        top.location.href = '/../solicitacoes/adicionarcontratacao/solicitacao_id/'+id+'/projeto_id/'+projeto_id;
        }
        else
        {
        top.location.href = '/../solicitacoes/adicionarpassagens/solicitacao_id/'+id+'/projeto_id/'+projeto_id;
        }
    }
</script>

<?php
$id = $this->id;
$tipo = $this->tipo;
$projeto_id = $this->pid;

echo "<button onclick='confirmarExclusao($id, $tipo, $projeto_id)'>Excluir</button>";
echo "<button onclick='editar($id, $tipo, $projeto_id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;

?>
