<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<script>
    $(document).ready(function() {
        $('#table_id_todas').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }

        });

        $('#table_id_aquisicao').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });

        $('#table_id_contratacao').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }

        });

        $('#table_id_passagens').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }

        });
    });
</script>
<script>
    function adicionaraquisicao()
    {
        top.location.href = '/../solicitacoes/adicionaraquisicao/';

    }
    function adicionarcontratacao()
    {
        top.location.href = '/../solicitacoes/adicionarcontratacao/';

    }
    function adicionarpassagens()
    {
        top.location.href = '/../solicitacoes/adicionarpassagens/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .passagens {
        float:right;
        padding: 7px;
    }
    .aquisicao {
        float:left;
        padding: 7px;
    }
    .contratacao {
        position:absolute;
        padding: 7px;
        left: 46%;
    }
</style>
<div class="botoes_superiores">
    <button class='passagens' onclick='adicionarpassagens()'>Adicionar Passagens e Diárias</button>
    <button class='contratacao' onclick='adicionarcontratacao()'>Adicionar Contratação de Serviços de Pessoa Física</button>
    <button class='aquisicao' onclick='adicionaraquisicao()'>Adicionar Aquisições de Bens e Serviços de Pessoa Jurídica</button>
</div>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Todas</a></li>
        <li><a href="#tabs-2">Aquisição de Bens e Serviços de Pessoa Jurídica</a></li>
        <li><a href="#tabs-3">Contratação de Serviços de Pessoa Física</a></li>
        <li><a href="#tabs-4">Passagens e Diárias</a></li>
    </ul>

    <div id="tabs-1">
        <table id='table_id_todas' border='0'>
            <thead>
            <tr>
                <th>Id</th>
                <th>NomeTODAS</th>
                <th>Data</th>
                <th>Projeto</th>
                <th>Coordenador</th>
                <th>Tipo</th>
                <th>Beneficiário</th>
<!--                <th>Valor total</th>-->
                <th>Local de entrega</th>
                <th>Resultados Esperados</th>
                <th>Objetivo</th>
                <th>Justificativa</th>
                <th>Observação</th>
            </tr>
            </thead>
        <tbody>

    <?php
    $filter = new Zend_Filter_DateFilter();
    foreach($this->solicitacoes as $row)
    {
        //$row = $row->toArray();
        echo "<tr id='".$row['solicitacao_id']."'>";
        echo "<td>" .   $row['solicitacao_id'] . "</td>";
        echo "<td><a href='/solicitacoes/detalhes/solicitacao_id/{$row['solicitacao_id']}'>" . $row['solicitacao_nome'] . "</a></td>";
        echo "<td>" .   $filter->filter($row['data_solicitacao']) . "</td>";
        echo "<td>" .   $row['p.nome'] . "</td>";
        echo "<td >" .  $row['cp.username'] . "</td>";
        echo "<td >" .  $row['ts.nome_tipo'] . "</td>";
        echo "<td >" .  $row['b.nome'] . "</td>";
        //echo "<td >" .  $row['preco_total'] . "</td>";
        echo "<td >" .  $row['local_entrega_solicitacao'] . "</td>";
        echo "<td >" .  $row['resultados_esperados'] . "</td>";
        echo "<td >" .  $row['objetivo_solicitacao'] . "</td>";
        echo "<td >" .  $row['justificativa'] . "</td>";
        echo "<td >" .  $row['observacao'] . "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>
    </div>

    <div id="tabs-2">
        <table id='table_id_aquisicao' border='0'>
            <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Data</th>
                <th>Projeto</th>
                <th>Coordenador</th>
                <th>Tipo</th>
                <th>Beneficiário</th>
<!--                <th>Valor total</th>-->
                <th>Local de entrega</th>
                <th>Resultados Esperados</th>
                <th>Objetivo</th>
                <th>Justificativa</th>
                <th>Observação</th>
            </tr>
            </thead>
            <tbody>

            <?php
            foreach($this->solicitacoesAquisicao as $row)
            {
                //$row = $row->toArray();
                echo "<tr id='".$row['solicitacao_id']."'>";
                echo "<td>" .   $row['solicitacao_id'] . "</td>";
                echo "<td><a href='/solicitacoes/detalhes/solicitacao_id/{$row['solicitacao_id']}'>" . $row['solicitacao_nome'] . "</a></td>";
                echo "<td>" .   $filter->filter($row['data_solicitacao']) . "</td>";
                echo "<td>" .   $row['p.nome'] . "</td>";
                echo "<td >" .  $row['cp.username'] . "</td>";
                echo "<td >" .  $row['ts.nome_tipo'] . "</td>";
                echo "<td >" .  $row['b.nome'] . "</td>";
//                echo "<td >" .  $row['preco_total'] . "</td>";
                echo "<td >" .  $row['local_entrega_solicitacao'] . "</td>";
                echo "<td >" .  $row['resultados_esperados'] . "</td>";
                echo "<td >" .  $row['objetivo_solicitacao'] . "</td>";
                echo "<td >" .  $row['justificativa'] . "</td>";
                echo "<td >" .  $row['observacao'] . "</td>";
                echo "</tr>";
            }
            echo "</tbody></table>";
            ?>
    </div>

    <div id="tabs-3">
        <table id='table_id_contratacao' border='0'>
            <thead>
            <tr>
                <th>Id</th>
                <th>NomeC</th>
                <th>Data</th>
                <th>Projeto</th>
                <th>Coordenador</th>
                <th>Tipo</th>
                <th>Beneficiário</th>
<!--                <th>Valor total</th>-->
                <th>Local de entrega</th>
                <th>Resultados Esperados</th>
                <th>Objetivo</th>
                <th>Justificativa</th>
                <th>Observação</th>
            </tr>
            </thead>
            <tbody>

            <?php
            foreach($this->solicitacoesContratacao as $row)
            {
                //$row = $row->toArray();
                echo "<tr id='".$row['solicitacao_id']."'>";
                echo "<td>" .   $row['solicitacao_id'] . "</td>";
                echo "<td><a href='/solicitacoes/detalhes/solicitacao_id/{$row['solicitacao_id']}'>" . $row['solicitacao_nome'] . "</a></td>";
                echo "<td>" .   $filter->filter($row['data_solicitacao']) . "</td>";
                echo "<td>" .   $row['p.nome'] . "</td>";
                echo "<td >" .  $row['cp.username'] . "</td>";
                echo "<td >" .  $row['ts.nome_tipo'] . "</td>";
                echo "<td >" .  $row['b.nome'] . "</td>";
//                echo "<td >" .  $row['preco_total'] . "</td>";
                echo "<td >" .  $row['local_entrega_solicitacao'] . "</td>";
                echo "<td >" .  $row['resultados_esperados'] . "</td>";
                echo "<td >" .  $row['objetivo_solicitacao'] . "</td>";
                echo "<td >" .  $row['justificativa'] . "</td>";
                echo "<td >" .  $row['observacao'] . "</td>";
                echo "</tr>";
            }
            echo "</tbody></table>";
            ?>
    </div>

    <div id="tabs-4">
        <table id='table_id_passagens' border='0'>
            <thead>
            <tr>
                <th>Id</th>
                <th>NomeP</th>
                <th>Data</th>
                <th>Projeto</th>
                <th>Coordenador</th>
                <th>Tipo</th>
                <th>Beneficiário</th>
<!--                <th>Valor total</th>-->
                <th>Local de entrega</th>
                <th>Resultados Esperados</th>
                <th>Objetivo</th>
                <th>Justificativa</th>
                <th>Observação</th>
            </tr>
            </thead>
            <tbody>

            <?php
            foreach($this->solicitacoesPassagens as $row)
            {
                //$row = $row->toArray();
                echo "<tr id='".$row['solicitacao_id']."'>";
                echo "<td>" .   $row['solicitacao_id'] . "</td>";
                echo "<td><a href='/solicitacoes/detalhes/solicitacao_id/{$row['solicitacao_id']}'>" . $row['solicitacao_nome'] . "</a></td>";
                echo "<td>" .   $filter->filter($row['data_solicitacao']) . "</td>";
                echo "<td>" .   $row['p.nome'] . "</td>";
                echo "<td >" .  $row['cp.username'] . "</td>";
                echo "<td >" .  $row['ts.nome_tipo'] . "</td>";
                echo "<td >" .  $row['b.nome'] . "</td>";
//                echo "<td >" .  $row['preco_total'] . "</td>";
                echo "<td >" .  $row['local_entrega_solicitacao'] . "</td>";
                echo "<td >" .  $row['resultados_esperados'] . "</td>";
                echo "<td >" .  $row['objetivo_solicitacao'] . "</td>";
                echo "<td >" .  $row['justificativa'] . "</td>";
                echo "<td >" .  $row['observacao'] . "</td>";
                echo "</tr>";
            }
            echo "</tbody></table>";
            ?>
    </div>
</div>