		<footer id="footer" >
		<section style="position:relative; float:none; margin-left:auto; margin-right:auto; display:block; width:980px; height:auto; color:#464646; font-family:unb_officeregular; font-size:10pt; font-style:normal; font-weight:lighter; text-rendering:geometricprecision; line-height:1.2em; text-shadow:rgba(0, 0, 0, 0.0976563) 0px 1px 1px; " >
			<figure style="float:left; margin-top:5px; " >
				<img src="/imagem/logo_cdt.png" class="footer_imagem" id="logo_cdt" style="" >
			</figure>
			<section style="float:left; text-align:right; padding-right:10px; padding-top:5px; " >	
				Universidade de Brasília - Edifício CDT <br>Campus Universitário Darcy Ribeiro <br>Brasília - Distrito Federal 		<br>Caixa 		Postal: 04397 Cep: 70904-970
			</section>
			<section style="float:left; text-align:left; padding-left:10px; padding-top:5px; " >	
				E-mail: atendimento@cdt.unb.br <br>Telefone: + 55 61 3107-4100 <br>Fax: + 55 61 3107-4136 
			</section>	
			<figure style="float:left; margin-top:5px; " >
				<img src="/imagem/logo_unb.png" class="footer_imagem" id="logo_unb" >
			</figure>
		<div style="clear:both; " ></div>
		</section>
	<div style="clear:both; " ></div>
	</footer>
