<div class="central">	
	<div id="topo"><a href="index"><img src="imagens/logo.png" /></a></div>
	<div class="menu">
		<ul class="menuTopo">
			<li><a href="/">HOME</a></li>
			<li><a href="/projetos">Projetos</a></li>
			<li><a href="#">Financeiro</a></li>
			<li><a href="#">Orçamentário</a></li>
			<li><a href="#">Contatos</a></li>
            <li><a href="/instituicoes">Instituições</a></li>
            <li><a href="/beneficiarios">Beneficiários</a></li>
		</ul>
	</div>
</div>	
