<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<script>
    $(document).ready(function() {
        $('#table_id_pf').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
        });

        $('#table_id_pj').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>

    function adicionar()
    {
        top.location.href = '/../beneficiarios/adicionar/';
    }

//    function funcaoFiltro(valor){
//        if(valor == 'cpf' ){
//            $('#table_id_pf_wrapper').css('display','block');
//            $('#table_id_pj_wrapper').css('display','none');
//        }
//        if(valor == 'cnpj' ){
//            $('#table_id_pj_wrapper').css('display','block');
//            $('#table_id_pf_wrapper').css('display','none');
//        }
//    }

</script>

<style>
    table * *{
        text-align: center;
    }
    .novobeneficiario {
        float:right;
    }
</style>

<div class="botoes_superiores">
    <button class='novobeneficiario btn_add' onclick='adicionar()'>Novo Beneficiario</button>
</div>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Pessoa Física</a></li>
        <li><a href="#tabs-2">Pessoa Jurídica</a></li>
    </ul>
    <div id="tabs-1">
        <table id='table_id_pf'>
            <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Endereço</th>
                <th>Telefone</th>
                <th>Banco</th>
                <th>E-mail</th>
                <th>RG</th>
                <th>Agência</th>
                <th>Conta</th>
                <th>NIT/PIS</th>
                <th>Escolaridade</th>
            </tr>
            </thead>
            <tbody>

            <?php
            foreach($this->beneficiariospf as $row){
                echo "<tr id='".$row['beneficiario_id']."'>";
                echo "<td>" .   $row['beneficiario_id'] . "</td>";
                echo "<td><a href='/beneficiarios/detalhespf/beneficiario_id/{$row['beneficiario_id']}'>" . $row['nome'] . "</a></td>";
                echo "<td>" .   $row['cpf_cnpj'] . "</td>";
                echo "<td >" .  $row['endereco'] . "</td>";
                echo "<td >" .  $row['telefone'] . "</td>";
                echo "<td >" .  $row['ba.nome_banco'] . "</td>";
                echo "<td >" .  $row['email'] . "</td>";
                echo "<td >" .   $row['rg_ie'] . "</td>";
                echo "<td>" .  $row['agencia_banco'] . "</td>";
                echo "<td >" .  $row['conta_bancaria'] . "</td>";
                echo "<td >" .  $row['nit_pis'] . "</td>";
                echo "<td >" .  $row['es.nome_escolaridade'] . "</td>";
                echo "</tr>";
            }
            ?>
            </tbody>
        </table>
    </div>
    <div id="tabs-2">
        <table id='table_id_pj'>
            <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>CNPJ</th>
                <th>Endereço</th>
                <th>Telefone</th>
                <th>Banco</th>
                <th>E-mail</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($this->beneficiariospj as $row){
                echo "<tr id='".$row['beneficiario_id']."'>";
                echo "<td>" .   $row['beneficiario_id'] . "</td>";
                echo "<td><a href='/beneficiarios/detalhespj/beneficiario_id/{$row['beneficiario_id']}'>" . $row['nome'] . "</a></td>";
                echo "<td>" .   $row['cpf_cnpj'] . "</td>";
                echo "<td >" .  $row['endereco'] . "</td>";
                echo "<td >" .  $row['telefone'] . "</td>";
                echo "<td >" .  $row['ba.nome_banco'] . "</td>";
                echo "<td >" .  $row['email'] . "</td>";
                echo "</tr>";
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
