<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar()
    {
        top.location.href = '/../beneficiarios/adicionar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novobeneficiario {
        float:right;
    }
</style>
<button class='novobeneficiario' onclick='adicionar()'>Novo Beneficiario</button>

<table id='table_id' border='1'>
    <thead>
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>CPF</th>
        <th>RG</th>
        <th>Endereço</th>
        <th>Telefone</th>
        <th>Banco</th>
        <th>Agência</th>
        <th>Conta</th>
        <th>NIT/PIS</th>
        <th>Escolaridade</th>
        <th>E-mail</th>
    </tr>
    </thead>
    <tbody>

    <?php
    foreach($this->beneficiarios as $row)
    {
        //$row = $row->toArray();
        echo "<tr id='".$row['beneficiario_id']."'>";
        echo "<td>" .   $row['beneficiario_id'] . "</td>";
        echo "<td><a href='/beneficiarios/detalhes/beneficiario_id/{$row['beneficiario_id']}'>" . $row['nome'] . "</a></td>";
        echo "<td>" .   $row['cpf_cnpj'] . "</td>";
        echo "<td>" .   $row['rg_ie'] . "</td>";
        echo "<td >" .  $row['endereco'] . "</td>";
        echo "<td >" .  $row['telefone'] . "</td>";
        echo "<td >" .  $row['banco_id'] . "</td>";
        echo "<td >" .  $row['agencia_banco'] . "</td>";
        echo "<td >" .  $row['conta_bancaria'] . "</td>";
        echo "<td >" .  $row['nit_pis'] . "</td>";
        echo "<td >" .  $row['escolaridade_id'] . "</td>";
        echo "<td >" .  $row['email'] . "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>