<script type="text/javascript" src="js/jquery.ui.combogrid-1.6.2.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $( "#empenhos-beneficiario").combogrid({
            debug:false,
            colModel: [{'columnName':'nome','width':'45','label':'Beneficiário'},{'columnName':'cpf_cnpj','width':'45','label':'CPF/CNPJ'}],
            url: 'empenhos/combogridbeneficiario/',
            select: function( event, ui ) {
                $("#empenhos-beneficiario").val( ui.item.nome );
                $("#empenhos-beneficiario_id").val( ui.item.beneficiario_id );
                return false;
            }
        });
    });


    function saldoOrcamentoDisponibilizado(id) {
        $.ajax({
            url: '/empenhos/saldoorcamentodisponibilizado/orcamento_id/'+id,
            dataType:'html',
            type:'GET',
            success: function(data){
                $('#empenhos-saldo_orcamento_disponibilizado').val(data);
                $('#empenhos-valor_empenho').attr('validators', array("Zend_Validate_Between2(array('min' => '0,00', 'max' => " + data + ")"))
            }
        })
    }
    
    function maskPre(val, msk, pre) {

        val = val.replace(RegExp('[' + msk.replace(/#/g, '') + ']', 'g'), '')

        if (val.length > 0) {
            val = pre + val
        }

        mskVal = ''
        v = val.length - 1
        for (m = msk.length - 1; m >= 0 && v >= -msk.indexOf('#'); --m) {
            if ('#' != msk.charAt(m)) {
                mskVal = msk.charAt(m) + mskVal
                if ('#' != msk.charAt(m - 1))
                    continue
                --m
            }
            mskVal = val.charAt(v) + mskVal
            v--

        }

        if (pre.length > 0) {
            mskVal = mskVal.replace(RegExp('^' + pre.charAt(0) + '+', 'g'), '')
        }

        return mskVal

    }
    
    function mask(val, msk) {

        return maskPre(val, msk, '')
    }
    
    function desabilitaTudo() {
        if ($("#empenhos-pre_empenho_id").is(':checked')) {
            $("#empenhos-processo_administrativo").attr('disabled', 'disabled');
            $("#empenhos-data").attr('disabled', 'disabled');
            $("#empenhos-beneficiario").attr('disabled', 'disabled');
            $("#empenhos-numero_parcelas").attr('disabled', 'disabled');
            $("#empenhos-data_inicio").attr('disabled', 'disabled');
            $("#empenhos-data_fim").attr('disabled', 'disabled');
        } else {
            $("#empenhos-processo_administrativo").attr('disabled', false);
            $("#empenhos-data").attr('disabled', false);
            $("#empenhos-beneficiario").attr('disabled', false);
            $("#empenhos-numero_parcelas").attr('disabled', false);
            $("#empenhos-data_inicio").attr('disabled', false);
            $("#empenhos-data_fim").attr('disabled', false);
        }
    }

</script>

<?php
    $this->form->setAction($this->url());
    echo $this->form;
?>