<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/<?php echo $projeto_id; ?>">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });
    });

</script>

<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir o projeto?");
        if (answer) {
            top.location.href = '/../empenhos/excluir/projeto_id/'+id;
        }
        else {
            alert("O empenho não foi excluído!");
        }
    }
</script>
<script>
    function editar(id)
    {
        top.location.href = '/../empenhos/adicionar/projeto_id/'+id;
    }
</script>

<?php
 $id = $this->id;

echo "<button onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>