<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
          //  "bProcessing": true,
          //  "sAjaxSource": 'empenhos/indexajax/projeto_id/'+id,
          //  "bDeferRender": true
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/'+<?php echo $projeto_id; ?>+'">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });

    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../empenhos/adicionar/projeto_id/'+projeto_id;

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novoprojeto {
        float:right;
    }
</style>


<?php
    echo "<button class='menu_financeiro'>Menu Financeiro</button>";
    echo "<button class='novoprojeto btn_add' onclick='adicionar($projeto_id)'>Novo Empenho</button>";
?>

<table id='table_id'>
    <thead>
    <tr>
        <th>Código Rubrica</th>
        <th>Natureza da despesa</th>
        <th>Data</th>
        <th>Processo administrativo</th>
        <th>Histórico</th>
        <th>Beneficiário</th>
        <th>Valor</th>
        <th>Número de Parcelas</th>
        <th>Data de Início da Bolsa</th>
        <th>Data do fim da Bolsa</th>
        <th>Valor Executado</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $somaRubrica = 0;
    $somaEmpenho = 0;
    $somaSaldoOrc = 0;
    $somaDesembolso = 0;
    $somaOrcamentoDisponibilizado = 0;
    $datefilter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();


    $orcamentoProjeto = $decimalfilter->filter($this->orcamentoProjeto[0]['p.orcamento']);
    $somaRubrica = number_format(0 + $this->soma[0]['valor_orcamento'], 2, '.', '');
    $valor_cronograma_orcamentario = number_format(0 + $this->soma[0]['valor'], 2, '.', '');
    $somaDesembolso = number_format(0 + $this->soma[0]['valor_desembolso'], 2, '.', '');
    $somaEmpenho = number_format(0 + ($this->soma[0]['SUM( e.valor_empenho )'] + $this->soma[0]['valor_pre_empenho']), 2, '.', '');
    $somaSaldoFin =  number_format(0 + ($this->soma[0]['valor_recebido'] - $somaDesembolso), 2, '.', '');
    $somaOrcamentoDisponibilizado = number_format($somaOrcamentoDisponibilizado + $valor_cronograma_orcamentario + 0, 2, '.', '');
    $somaSaldoOrc = number_format(0 + $somaOrcamentoDisponibilizado - $somaEmpenho , 2, '.', '');

    foreach($this->pre_empenhos as $row)
    {
        echo "<tr>";
        echo "<td>" . $row['codigo_rubrica'] . "</a></td>";
        echo "<td >" . $row['descricao'] . "</td>";
        echo "<td>" .  $datefilter->filter($row['data_pre_empenho']) . "</td>";
        echo "<td > Pré-Empenho </td>";
        echo "<td >" .  $row['pre_empenho_historico'] . "</td>";
        echo "<td > - </td>";
        echo "<td >" .  $decimalfilter->filter($row['valor_pre_empenho']) . "</td>";
        echo "<td > - </td>";
        echo "<td > - </td>";
        echo "<td > - </td>";
        echo "<td > 0,00 </td>";
        echo "</tr>";
    }

    foreach($this->resultado as $row)
    {
    echo "<tr id='".$row['empenho_id']."'>";
    echo "<td><a href='/empenhos/detalhes/empenho_id/{$row['empenho_id']}/projeto_id/{$row['projeto_id']}'>" . $row['codigo_rubrica'] . "</a></td>";
    echo "<td >" .  $row['rubrica_descricao'] . "</td>";
    echo "<td>" .   $datefilter->filter($row['data']) . "</td>";
    echo "<td >" .  $row['processo_administrativo'] . "</td>";
    echo "<td >" .  $row['descricao_historico'] . "</td>";
    echo "<td >" .  $row['beneficiario_nome'] . "</td>";
    echo "<td >" .  $decimalfilter->filter($row['valor_empenho']) . "</td>";
    echo "<td >" .  $row['numero_parcelas'] . "</td>";
    echo "<td >" .  $datefilter->filter($row['data_inicio']) . "</td>";
    echo "<td >" .  $datefilter->filter($row['data_fim']) . "</td>";
    echo "<td >" .  $decimalfilter->filter(number_format(0 + $row['valor_executado'], 2, '.', '')) . "</td>";
    echo "</tr>";
    }

    echo "</tbody></table>";

    echo "</br>";
    echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
    echo "<thead style='background-color: #E2E4FF;'>";
    echo "<tr>";
    echo "<th> Orçamento Previsto</th>";
    echo "<th> Total Rubrica</th>";
    echo "<th> Orçamento Disponibilizado</th>";
    echo "<th> Total Empenhado</th>";
    echo "<th> Saldo Orçamentário</th>";
    echo "<th> Saldo Financeiro</th>";
    echo "</tr>";
    echo "</thead>";

    echo "<tbody style='color:green;'>";
    echo "<tr>";
    echo "<td>" . $orcamentoProjeto . "</td>";
    echo "<td>" . $decimalfilter->filter($somaRubrica) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaOrcamentoDisponibilizado) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaEmpenho) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaSaldoOrc) . "</td>";
    echo "<td>" . $decimalfilter->filter($somaSaldoFin) . "</td>";

    echo "</tr>";
    echo "</tbody>";
    echo "</table>";
    echo "</br></br></br>";
?>

