<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
          //  "bProcessing": true,
          //  "sAjaxSource": 'empenhos/indexajax/projeto_id/'+id,
          //  "bDeferRender": true
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });

    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../empenhos/adicionar/projeto_id/'+projeto_id;

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novoprojeto {
        float:right;
    }
</style>


<?php
    $projeto_id = $this->id;
    echo "<button class='novoprojeto btn_add' onclick='adicionar($projeto_id)'>Novo Empenho</button>";
?>

<table id='table_id'>
    <thead>
    <tr>
        <th>Código Rubrica</th>
        <th>Data</th>
        <th>Beneficiário</th>
        <th>Valor</th>
        <th>Número de Parcelas</th>
        <th>Data de Início da Bolsa</th>
        <th>Data do fim da Bolsa</th>
        <th>Orcamento</th>
        <th>Usuário</th>
        <th>Pré Empenho</th>
    </tr>
    </thead>
    <tbody>

    <?php
    foreach($this->resultado as $row)
    {
    //$row = $row->toArray();
    echo "<tr id='".$row['empenho_id']."'>";
    echo "<td><a href='/projetos/detalhes/projeto_id/{$row['projeto_id']}'>" . $row['codigo_rubrica'] . "</a></td>";
    echo "<td>" .   $row['data'] . "</td>";
    echo "<td >" .  $row['beneficiario_id'] . "</td>";
    echo "<td >" .  $row['valor_empenho'] . "</td>";
    echo "<td >" .  $row['numero_parcelas'] . "</td>";
    echo "<td >" .  $row['data_inicio'] . "</td>";
    echo "<td >" .  $row['data_fim'] . "</td>";
    echo "<td >" .  $row['orcamento_id'] . "</td>";
    echo "<td >" .  $row['usuario_id'] . "</td>";
    echo "<td >" .  $row['pre_empenho_id'] . "</td>";
    echo "</tr>";
    }
    echo "</tbody></table>";
?>

