<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir a tarefa?");
        if (answer) {
            top.location.href = '/../tarefasporprojeto/excluir/tarefa_id/'+id;
        }
        else {
            alert("A tarefa não foi excluída!");
        }
    }
</script>
<script>
    function editar(id)
    {
        top.location.href = '/../tarefas/adicionar/tarefa_id/'+id;

    }
</script>

<?php
 $id = $this->id;

echo "<button class=\"right btn_delete\" onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button class=\"right btn_edit\" onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
?>