<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir o projeto?");
        if (answer) {
            top.location.href = '/../projetos/excluir/projeto_id/'+id;
        }
        else {
            alert("O projeto não foi excluído!");
        }
    }
</script>
<script>
    function editar(id)
    {
        top.location.href = '/../projetos/adicionar/projeto_id/'+id;

    }
    function termoAditivo(id)
    {
        top.location.href = '/../termoaditivo/index/projeto_id/'+id;

    }
</script>

<?php
 $id = $this->id;

echo "<button onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button onclick='editar($id)'>Editar</button>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;
echo "<button class='termo_aditivo' onclick='termoAditivo($id)'>Termo Aditivo do Projeto</button>";
?>
