
<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    function confirmarExclusao(id)
    {
        var answer = confirm("Deseja realmente excluir o projeto?");
        if (answer) {
            top.location.href = '/../projetos/excluir/projeto_id/'+id;
        }
        else {
            alert("O projeto não foi excluído!");
        }
    }

    function editar(id)
    {
        top.location.href = '/../projetos/adicionar/projeto_id/'+id;

    }
    function termoAditivo(id)
    {
        top.location.href = '/../termoaditivo/index/projeto_id/'+id;

    }
    function cronogramaFinanceiro(id)
    {
        top.location.href = '/../cronogramafinanceiro/index/projeto_id/'+id;
    }
    function tarefasProjeto(id)
    {
        top.location.href= '/../tarefas/index/projeto_id/'+id;
    }
    function orcamentos(id)
    {
        top.location.href = '/../orcamentos/index/projeto_id/'+id;
    }
    function cronogramaOrcamentario(id)
    {
        top.location.href= '/../cronogramaorcamentario/index/projeto_id/'+id;
    }
    function empenhos(id)
    {
        top.location.href = '/../empenhos/index/projeto_id/'+id;
    }
    function desembolso(id)
    {
        top.location.href = '/../desembolso/index/projeto_id/'+id;
    }
    function solicitacoes(id)
    {
        top.location.href = '../solicitacoes/index/projeto_id/'+id;
    }
</script>

<?php
 $id = $this->id;

echo "<button class=\"right btn_delete\" onclick='confirmarExclusao($id)'>Excluir</button>";
echo "<button class=\"right btn_edit\" onclick='editar($id)'>Editar</button>";

echo "<div class='menufinanceiro'>";
echo "<button class='btn_financeiro' onclick='orcamentos($id)'><img src='imagens/icones/orcamento.png'>Orçamento</button>";
echo "<button class='btn_financeiro' onclick='termoAditivo($id)'><img src='imagens/icones/termoaditivo.png'>Termo Aditivo do Projeto</button>";
echo "<button class='btn_financeiro' onclick='cronogramaFinanceiro($id)'><img src='imagens/icones/cronogramafinanceiro.png'>Cronograma Financeiro</button>";
echo "<button class='btn_financeiro' onclick='tarefasProjeto($id)'><img src='imagens/icones/tarefa.png'>Tarefas</button>";
echo "<button class='btn_financeiro' onclick='cronogramaOrcamentario($id)'><img src='imagens/icones/cronogramaorcamentario.png'>Cronograma Orçamentário</button>";
echo "<button class='btn_financeiro' onclick='empenhos($id)'><img src='imagens/icones/empenho.png'>Empenho</button>";
echo "<button class='btn_financeiro' onclick='desembolso($id)'><img src='imagens/icones/desembolso.png'>Desembolso</button>";
echo "<button class='btn_financeiro' onclick='solicitacoes($id)'><img src='imagens/icones/solicitacao.png'>Solicitações</button>";
echo "</div>";

$this->detalhes->setAction($this->url());
echo $this->detalhes;

?>
