<script type="text/javascript" src='js/detalhes.js'></script>
<script>
    $('a.fancybox-item.fancybox-close').click(function (){
        parent.$.fancybox.close();
    });


    function termoAditivo(id)
    {
        top.location.href = '/../termoaditivo/index/projeto_id/'+id;

    }
    function cronogramaFinanceiro(id)
    {
        top.location.href = '/../cronogramafinanceiro/index/projeto_id/'+id;
    }
    function tarefasProjeto(id)
    {
        top.location.href= '/../tarefas/index/projeto_id/'+id;
    }
    function orcamentos(id)
    {
        top.location.href = '/../orcamentos/index/projeto_id/'+id;
    }
    function cronogramaOrcamentario(id)
    {
        top.location.href= '/../cronogramaorcamentario/index/projeto_id/'+id;
    }
    function empenhos(id)
    {
        top.location.href = '/../empenhos/index/projeto_id/'+id;
    }
    function desembolso(id)
    {
        top.location.href = '/../desembolso/index/projeto_id/'+id;
    }
    function solicitacoes(id)
    {
        top.location.href = '/../solicitacoes/index/projeto_id/'+id;
    }
</script>

<?php
$id = $this->id;

echo "<button class='' onclick='termoAditivo($id)'><img src='imagens/icones/termoaditivo.png'>Termo Aditivo do Projeto</button>";
echo "<button class='' onclick='cronogramaFinanceiro($id)'><img src='imagens/icones/cronogramafinanceiro.png'>Cronograma Financeiro</button>";
echo "<button class='' onclick='tarefasProjeto($id)'><img src='imagens/icones/tarefa.png'>Tarefas</button>";
echo "<button class='' onclick='orcamentos($id)'><img src='imagens/icones/orcamento.png'>Orcamento</button>";
echo "<button class='' onclick='cronogramaOrcamentario($id)'><img src='imagens/icones/cronogramaorcamentario.png'>Cronograma Orçamentário</button>";
echo "<button class='' onclick='empenhos($id)'><img src='imagens/icones/empenho.png'>Empenho</button>";
echo "<button class='' onclick='desembolso($id)'><img src='imagens/icones/desembolso.png'>Desembolso</button>";
echo "<button class='' onclick='solicitacoes($id)'><img src='imagens/icones/solicitacao.png'>Solicitações</button>";


?>