<?php
    print_r($this->prioridade);

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->modoContratacao);

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->projetoTipo);

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->instituicao);

    echo "<br/><br/><br/><br/><br/><br/>";

//    print_r($this->estadoProjeto);
//
//    echo "<br/><br/><br/><br/><br/><br/>";
//
//    print_r($this->categoriaFinanciador);

?>