<?php
    print_r($this->prioridade->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->modoContratacao->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->projetoTipo->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->instituicao->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

//    print_r($this->estadoProjeto->toArray());
//
//    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->categoriaFinanciador->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->coordenador->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->gerente->toArray());

    echo "<br/><br/><br/><br/><br/><br/>";

    print_r($this->criador->toArray());
?>