<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../tarefas/adicionar/projeto_id/'+projeto_id;
    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novatarefa {
        float:right;
    }
</style>
<?php
$projeto_id = $this->pid;

echo "<button class='novatarefa btn_add' onclick='adicionar($projeto_id)'>Nova Tarefa</button>";

?>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Id</th>
        <th>Porcentagem Completa</th>
        <th>Projeto</th>
        <th>Nome da Tarefa</th>
        <th>Responsável da Tarefa</th>
        <th>Data de início</th>
        <th>Data de final</th>
        <th>Duração(dias)</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $filter = new Zend_Filter_DateFilter();
    foreach($this->tarefas as $row)
    {
        $dataAtual=date("Y-m-d H:i:s ");
        if(($dataAtual>$row['data_final']) && ($row['percentagem_completo']='100'))
        {
            // vermelho, já terminou
            $cor='#CC6666';
            $corletra='#ffffff';
        }else{
            //verde, ainda esta sendo desenvolvido
            $cor='#AADDAA';
            $corletra='#000000';
        }

        //$row = $row->toArray();
        echo "<tr id='".$row['tarefa_id']."'>";
        echo "<td>" .   $row['tarefa_id'] . "</td>";
        echo "<td >" .  $row['percentagem_completo'] . "</td>";
        echo "<td>" .   $row['nomeprojeto'] . "</td>";
        echo "<td><a href='/tarefas/detalhes/tarefa_id/{$row['tarefa_id']}'>" . $row['nome'] . "</a></td>";
        echo "<td>" .   $row['username'] . "</td>";
        echo "<td style='background: $cor; color:$corletra'>" .   $filter->filter($row['data_inicio']) . "</td>";
        echo "<td style='background: $cor; color:$corletra'>" .   $filter->filter($row['data_final']) . "</td>";
        echo "<td style='background: $cor; color:$corletra'>" .  $row['duracao'] . "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>
    <table>
        <tbody>
            <tr>
                <td width="15" style="background-color:#AADDAA;"></td>
                <td>Em desenvolvimento</td>
                <td width="15" style="background-color:#CC6666;"></td>
                <td>Finalizado</td>
            </tr>
        </tbody>
    </table>
