<?php
$projeto_id = $this->pid;
?>

<script>
    $(document).ready(function() {
        //jQuery('#table_id').treetable('expandAll');
        $("#table_id").treetable({ expandable: false });
    });
</script>

<script>

    function adicionar($projeto_id)
    {
        if($projeto_id==null)
        {
            top.location.href = "/../tarefas/adicionar/";
        }else
        {
            top.location.href = "/../tarefas/adicionar/projeto_id/"+$projeto_id;
        }

    }

</script>
<style>
    table * *{
        text-align: left;
    }
    .novatarefa {
        float:right;
    }
</style>
<?php
//$projeto_id = $this->pid;
//
//echo "<button class='novatarefa btn_add' onclick='adicionar($projeto_id)'>Nova Tarefa</button>";
//
//?>

<button class='novatarefa btn_add' onclick='adicionar(<?php echo $projeto_id; ?>)'>Nova Tarefa</button>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Nome da Tarefa</th>
        <th>Porcentagem Completa</th>
        <th>Projeto</th>
        <th>Responsável da Tarefa</th>
        <th>Data de início</th>
        <th>Data de final</th>
        <th>Duração(dias)</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $filter = new Zend_Filter_DateFilter();

    foreach($this->tarefas as $row)
    {
        $dataAtual=date("Y-m-d H:i:s ");
        if(($dataAtual>$row['data_final']) && ($row['percentagem_completo']='100'))
        {
            // vermelho, já terminou
            $cor='#CC6666';
            $corletra='#ffffff';
        }else{
            //verde, ainda esta sendo desenvolvido
            $cor='#AADDAA';
            $corletra='#000000';
        }

        //configura ids de tarefas hierarquicas
        if($row['tarefa_id_pai']=='0')
        {
            echo "<tr data-tt-id='".$row['tarefa_id']."'>";
        }else
        {
            echo "<tr data-tt-id='".$row['tarefa_id']."' data-tt-parent-id='".$row['tarefa_id_pai']."'>";
        }
        echo "<td><a href='/tarefas/detalhes/tarefa_id/{$row['tarefa_id']}'>" . $row['nome_tarefa'] . "</a></td>";
        //echo "<td>" .   $row['tarefa_id'] . "</td>";
        echo "<td >" .  $row['porcentagem'] . "</td>";
        echo "<td>" .   $row['nome_projeto'] . "</td>";
        echo "<td>" .   $row['responsavel_tarefa'] . "</td>";
        echo "<td style='background: $cor; color:$corletra'>" .   $filter->filter($row['data_inicio']) . "</td>";
        echo "<td style='background: $cor; color:$corletra'>" .   $filter->filter($row['data_final']) . "</td>";
        echo "<td style='background: $cor; color:$corletra'>" .  $row['duracao'] . "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>
    <table>
        <tbody>
            <tr>
                <td width="15" style="background-color:#AADDAA;"></td>
                <td>Em desenvolvimento</td>
                <td width="15" style="background-color:#CC6666;"></td>
                <td>Atrasado</td>
            </tr>
        </tbody>
    </table>
