<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar()
    {
        top.location.href = '/../tarefas/adicionar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novatarefa {
        float:right;
    }
</style>
<button class='novatarefa btn_add' onclick='adicionar()'>Nova Tarefa</button>

<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Id</th>
        <th>Porcentagem Completa</th>
        <th>Projeto</th>
        <th>Nome da Tarefa</th>
        <th>Dono</th>
        <th>Data de início</th>
        <th>Duração</th>
    </tr>
    </thead>
    <tbody>

    <?php
    $filter = new Zend_Filter_DateFilter();
    foreach($this->tarefas as $row)
    {
        //$row = $row->toArray();
        echo "<tr id='".$row['tarefa_id']."'>";
        echo "<td>" .   $row['tarefa_id'] . "</td>";
        echo "<td >" .  $row['percentagem_completo'] . "</td>";
        echo "<td>" .   $row['pr.nome'] . "</td>";
        echo "<td><a href='/tarefas/detalhes/tarefa_id/{$row['tarefa_id']}'>" . $row['nome'] . "</a></td>";
        echo "<td>" .   $row['us.username'] . "</td>";
        echo "<td>" .   $filter->filter($row['data_inicio']) . "</td>";
        echo "<td >" .  $row['duracao'] . "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>