<?php
$projeto_id = $this->pid;
?>

<style>
    body { font-size: 62.5%; }
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>
  
<div id="dialog-form" title="Receber valor">
  <p class="validateTips">Preencha todos os campos.</p>
 
  <form>
  <fieldset>
    <label for="date">Data de recebimento:</label>
    <input type="text" name="date" id="date" class="text ui-widget-content ui-corner-all " />
    <label for="valor">Valor:</label>
    <input type="text" name="valor" id="valor" value="" class="text ui-widget-content ui-corner-all" maxlength="13" onkeyup="this.value=mask(this.value, '###.###.###,##')" />
  </fieldset>
  </form>
</div>
 
<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
        $('.fancybox').fancybox();
        $('button.menu_financeiro').click(function() {
            $('<a class="fancybox fancybox.iframe" href="projetos/fancyboxmenufinanceiro/projeto_id/<?php echo $projeto_id; ?>">pesquisar</a>').fancybox({
                overlayShow: true
            }).click();
        });

        $("#date").datepicker({"dateFormat":"dd\/mm\/yy","dayNamesMin":["D","S","T","Q","Q","S","S"],"monthNames":["Janeiro","Fevereiro","Mar\u00e7o","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]});
        
    });
    
    function maskPre(val, msk, pre) {

        val = val.replace(RegExp('[' + msk.replace(/#/g, '') + ']', 'g'), '')

        if (val.length > 0) {
            val = pre + val
        }

        mskVal = ''
        v = val.length - 1
        for (m = msk.length - 1; m >= 0 && v >= -msk.indexOf('#'); --m) {
            if ('#' != msk.charAt(m)) {
                mskVal = msk.charAt(m) + mskVal
                if ('#' != msk.charAt(m - 1))
                    continue
                --m
            }
            mskVal = val.charAt(v) + mskVal
            v--

        }

        if (pre.length > 0) {
            mskVal = mskVal.replace(RegExp('^' + pre.charAt(0) + '+', 'g'), '')
        }

        return mskVal

    }
    
    function mask(val, msk) {

        return maskPre(val, msk, '')
    }
</script>
<script>
    function adicionar(projeto_id)
    {
        top.location.href = '/../cronogramafinanceiro/adicionar/projeto_id/'+projeto_id;

    }
    
    function receber(id, pid)
    {
        if (confirm("O valor previsto será transformado em valor recebido. Confirmar?")) {
            top.location.href = '/../cronogramafinanceiro/receber/cronograma_financeiro_id/'+id+'/projeto_id/'+pid;
        }
    }

    function editar(id, pid)
    {
        top.location.href = '/../cronogramafinanceiro/adicionar/cronograma_financeiro_id/'+id+'/projeto_id/'+pid;
    }

    function confirmarExclusao(id, pid)
    {
        var answer = confirm("Deseja realmente excluir o cronograma?");
        if (answer) {
            top.location.href = '/../cronogramafinanceiro/excluir/cronograma_financeiro_id/'+id+'/projeto_id/'+pid;
        }
        else {
            alert("O cronograma não foi excluído!");
        }
    }

</script>
<style>
    table * *{
        text-align: center;
    }
    .novaparcela {
        float:right;
    }
</style>
<?php
    echo "<button class='menu_financeiro'>Menu Financeiro</button>";
    echo "<button class='novaparcela btn_add' onclick='adicionar($projeto_id)'>Nova Parcela</button>";
?>
<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Data Prevista</th>
        <th>Valor Previsto</th>
        <th>Valor Recebido</th>
        <th>Tipo</th>
        <th>Fatura/PF</th>
        <th>Data Pagamento</th>
        <th>Receber valor</th>
        <th>Editar</th>
        <th>Excluir</th>
<!--        <th>Data final real</th>-->
<!--        <th>Estado do projeto</th>-->
<!--        <th>Porcentagem completa</th>-->
<!--        <th>Prioridade</th>-->
<!--        <th>Coordenador técnico</th>-->
    </tr>
    </thead>
    <tbody>

    <?php

    $datefilter = new Zend_Filter_DateFilter();
    $decimalfilter = new Zend_Filter_DecimalFilter();

    //$totalPrevisto = $decimalfilter->filter($this->total[0]['SUM( c.valor_a_receber )']);
    //$totalRecebido = $decimalfilter->filter($this->total[0]['SUM( c.valor_recebido )']);

    $totalPrevisto = 0;
    $totalRecebido = 0;

    foreach($this->cronogramaFinanceiro as $row)
    {

    $totalPrevisto += $row['valor_aplicado_a_rubrica'];
    $totalRecebido += $row['valor_recebido'];
    //$row = $row->toArray();
    echo "<tr id='".$row['cronograma_financeiro_id']."'>";
        echo "<td>" .   $datefilter->filter($row['data_previa']) . "</td>";
        echo "<td>" .   $decimalfilter->filter($row['valor_aplicado_a_rubrica']) . "</td>";
        echo "<td><a href='/cronogramafinanceiro/detalhes/cronograma_financeiro_id/{$row['cronograma_financeiro_id']}/projeto_id/{$projeto_id}'>" .   $decimalfilter->filter($row['valor_recebido']) . "</a></td>";

        if($row['tipo'] == 1)
        {
            echo "<td> Fatura</td>";
        }
        if($row['tipo'] == 2)
        {
            echo "<td> PF</td>";
        }

    echo "<td>" .   $row['numero_fatura_pf'] . "</td>";

        if ($row['data_pagamento'] == null)
        {
            echo "<td>---</td>";
        }
        else
        {
            echo "<td>" . $datefilter->filter($row['data_pagamento']) . "</td>";
        }
//    echo "<td><a class='\right btn_edit\' href='/cronogramafinanceiro/adicionar/projeto_id/".$projeto_id."/cronograma_financeiro_id/"
//    ."{$row['cronograma_financeiro_id']}'>aa</a></td>";
//    echo "<td><a class='\right btn_delete\' href='/cronogramafinanceiro/excluir/cronograma_financeiro_id/{$row['cronograma_financeiro_id']}'>bb</a></td>";
    //echo "<td><button class=\"center btn_receive\" onclick='receber(".$row['cronograma_financeiro_id'].", ".$projeto_id.")'>Receber</button>";
    echo "<td><button id=\"create-user<?php echo $i; ?>\" class=\"create-user\">Receber</button>";
        
    echo "<td><button class=\"center btn_edit\" onclick='editar(".$row['cronograma_financeiro_id'].", ".$projeto_id.")'>Editar</button>";
    echo "<td><button class=\"center btn_delete\" onclick='confirmarExclusao(".$row['cronograma_financeiro_id'].", ".$projeto_id.")'>Editar</button>";

//    echo "<td>" .   $row['ga.nome_instituicao_gerencia'] . "</td>";
//    echo "<td><a href='/projetos/detalhes/projeto_id/{$row['projeto_id']}'>" . $row['nome'] . "</a></td>";
//    echo "<td>" .   $row['apelido'] . "</td>";
//    echo "<td >" .  $filter->filter($row['data_inicio']) . "</td>";
//    echo "<td >" .  $filter->filter($row['data_final']) . "</td>";
//    echo "<td >" .  $filter->filter($row['data_final_real']) . "</td>";
//    echo "<td >" .  $row['nome_estado'] . "</td>";
//    echo "<td >" .  $row['percentagem_completo'] . "</td>";
//    echo "<td >" .  $row['nome_prioridade'] . "</td>";
//    echo "<td >" .  $row['ct.sobrenome'] . "</td>";
    echo "</tr>";
    }
    echo "</tbody></table>";

    echo "</br>";
    echo "<table id='tabela' width='80%' border='0px;' style='left:10%; position:relative; font-size:14px;' >";
    echo "<thead style='background-color: #E2E4FF;'>";
    echo "<tr>";
    echo "<th> Total Previsto</th>";
    echo "<th> Total Recebido</th>";
    //echo "<th> Índice de Realização das Parcelas</th>";
    echo "</tr>";
    echo "</thead>";

    echo "<tbody style='color:green;'>";
    echo "<tr>";
    echo "<td>" . $decimalfilter->filter(number_format(0 + $totalPrevisto, 2, '.', '')) . "</td>";
    echo "<td>" . $decimalfilter->filter(number_format(0 + $totalRecebido, 2, '.', '')) . "</td>";
    //echo "<td>" . number_format(0 + ($pagas/($i - 1)) * 100, 2, '.', '') . "%</td>";

    echo "</tr>";
    echo "</tbody>";
    echo "</table>";
    echo "</br></br></br>";
?>