<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar()
    {
        top.location.href = '/../cronogramafinanceiro/adicionar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novaparcela {
        float:right;
    }
</style>
    <button class='novaparcela btn_add' onclick='adicionar()'>Nova Parcela</button>
<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Id</th>
        <th>Projeto</th>
        <th>Valor</th>
        <th>Data</th>
        <th>Tipo</th>
        <th>Fatura</th>
<!--        <th>Data final real</th>-->
<!--        <th>Estado do projeto</th>-->
<!--        <th>Porcentagem completa</th>-->
<!--        <th>Prioridade</th>-->
<!--        <th>Coordenador técnico</th>-->
    </tr>
    </thead>
    <tbody>

    <?php
    $filter = new Zend_Filter_DateFilter();
    foreach($this->cronogramaFinanceiro as $row)
    {
    //$row = $row->toArray();
    echo "<tr id='".$row['cronograma_financeiro_id']."'>";
    echo "<td><a href='/cronogramafinanceiro/detalhes/cronograma_financeiro_id/{$row['cronograma_financeiro_id']}'>"
        .$row['cronograma_financeiro_id']. "</a></td>";
    echo "<td>" .   $row['p.nome'] . "</td>";
    echo "<td>" .   $row['valor_aplicado_a_rubrica'] . "</td>";
    echo "<td>" .   $row['data_previa'] . "</td>";
    echo "<td>" .   $row['tipo'] . "</td>";
    echo "<td>" .   $row['numero_fatura_pf'] . "</td>";

//    echo "<td>" .   $row['ga.nome_instituicao_gerencia'] . "</td>";
//    echo "<td><a href='/projetos/detalhes/projeto_id/{$row['projeto_id']}'>" . $row['nome'] . "</a></td>";
//    echo "<td>" .   $row['apelido'] . "</td>";
//    echo "<td >" .  $filter->filter($row['data_inicio']) . "</td>";
//    echo "<td >" .  $filter->filter($row['data_final']) . "</td>";
//    echo "<td >" .  $filter->filter($row['data_final_real']) . "</td>";
//    echo "<td >" .  $row['nome_estado'] . "</td>";
//    echo "<td >" .  $row['percentagem_completo'] . "</td>";
//    echo "<td >" .  $row['nome_prioridade'] . "</td>";
//    echo "<td >" .  $row['ct.sobrenome'] . "</td>";
    echo "</tr>";
    }
    echo "</tbody></table>";
?>