<style>
    .novoprojeto {
        float:right;
    }
</style>
<button class='novoprojeto btn_back' onclick='voltar()'>Voltar</button>
<script type="text/javascript">

    function atualizarTarefas(valor) {

        if(valor!=0){
            $.ajax({
                url: '/arquivos/selecttarefas/id/'+valor,
                dataType:'html',
                type:'GET',
                success: function(data){
                    $('select#arquivos-tarefa_id').html(data);
                }
            })
        }


    }

    function voltar()
    {
        top.location.href = '/../arquivos/';
    }

</script>

<?php
$this->form->setAction($this->url());
echo $this->form;
?>

