<script type="text/javascript">
    function atualizarTarefas(valor) {
        if(valor !== 0){
            $.ajax({
                url: '/arquivos/selecttarefas/id/'+valor,
                dataType:'html',
                type:'GET',
                success: function(data){
                    $('select#arquivos-tarefa_id').html(data);
                }
            })
        }
    }
</script>

<?php
//nmjjjj
$this->form->setAction($this->url());
echo $this->form;
?>