<script type="text/javascript">
    function atualizarTarefas(valor) {
            $.ajax({
                url: '/arquivos/selecttarefas/id/'+valor,
                dataType:'html',
                type:'GET',
                success: function(data){
                    $('select#arquivos-tarefa_id').html(data);
                }
            })
    }
</script>
<?php
$this->form->setAction($this->url());
echo $this->form;
?>