<script>
    $(document).ready(function() {
        $('#table_id').dataTable({
            "sDom": 'R<"H"lfr>t<"F"ip<',
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostra _MENU_ Entradas por Página",
                "sZeroRecords": "Nada Encontrado",
                "sInfo": "Mostrando de _START_ até _END_ do total de _TOTAL_ ",
                "sEmptyTable": "Nenhum Dado Disponível na Tabela",
                "sLoadingRecords": "Carregando...",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 Entradas",
                "sInfoFiltered": "(Filtrados de _MAX_ Total de Entradas)",
                "sSearch": "BUSCA",
                "oPaginate": {
                    "sFirst":    " <<  ",
                    "sPrevious": " < ",
                    "sNext":     " > ",
                    "sLast":     " >> "
                }
            }
            //"bSort": false,
//            "aaSorting": [ [4,'desc'], [1,'asc'], [2,'asc'], [3,'asc']  ],
//            "aoColumns": [
//                { "sType": 'string-case' },
//                null,
//                null,
//                null,
//                null,
//            ]
        });
    });
</script>
<script>
    function adicionar()
    {
        top.location.href = '/../arquivos/adicionar/';

    }
</script>
<style>
    table * *{
        text-align: center;
    }
    .novoprojeto {
        float:right;
    }
</style>
<button class='novoprojeto' onclick='adicionar()'>Novo Arquivo</button>


<table id='table_id' border='0'>
    <thead>
    <tr>
        <th>Nome de Arquivo</th>
        <th>Descriçao</th>
        <th>Versões</th>
        <th>Tipo de Arquivo</th>
        <th>Download</th>
        <th>Nome da Tarefa</th>
        <th>Responsável</th>
        <th>Tamanho</th>
        <th>Data</th>
    </tr>
    </thead>
    <tbody>

<?php
    $array=$this->arquivos;
    $nro=count($array);

    for($i=0;$i<$nro;$i++)
    {
        $arquivoId= $array[$i]['a.arquivo_id'];
        $projetoId= $array[$i]['a.projeto_id'];
        $tarefa=$array[$i]['t.tarefa_id'];

        // fazer o caminho para cada link
        if($tarefa)
        {
            // existe tarefa, então o caminho é
            $ruta = 'files/arquivos/projeto-'.$projetoId.'/tarefa-'.$tarefa.'/'.$array[$i]['a.nome_arquivo'];
        }else
        {
            // ruta para projeto so
            $ruta = 'files/arquivos/projeto-'.$projetoId.'/'.$array[$i]['a.nome_arquivo'];
        }

        // criamos a tabela com os registros
        echo "<tr id='".$array[$i]['a.arquivo_id']."'>";
        echo "<td><a href='/arquivos/detalhes/arquivo_id/{$array[$i]['a.arquivo_id']}'>" .$array[$i]['a.nome_arquivo']. "</a></td>";
        echo "<td>" .$array[$i]['a.descricao_arquivo']. "</td>";
        echo "<td>" .$array[$i]['a.versao']. "</td>";
        echo "<td>" .$array[$i]['ta.nome_tipo']. "</td>";
        echo "<td><a href='".$ruta."' >" .$array[$i]['a.nome_arquivo']. "</a></td>";
        echo "<td>" .$array[$i]['t.nome']. "</td>";
        echo "<td>" .$array[$i]['u.nome']. "</td>";
        echo "<td>" .$array[$i]['a.tamanho']. "</td>";
        echo "<td>" .$array[$i]['a.data_arquivo']. "</td>";
        echo "</tr>";
    }
    echo "</tbody></table>";
?>